### ISSUE TITLE
Start SAP HANA, express edition Server

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2367] opened 2018-05-25 07:49 UTC
​The latest installation procedure of SAP HANA 2.0 SPS3 on VM is absolutely unreliable. It continuously fail on different steps with weird error messages related to internal jdbc and ports connection errors. Ever they are unpredictable the all relate to error getting authentication token from UAA. The last one I've got is 
>TLS certificate validation failed HDB_CONN_TLS_CERT_VALIDATION_FAILED ERROR Failed to register "SystemDB" database to Cockpit
> 
which is similar to unanswered question since January 2018 https://answers.sap.com/questions/394239/failed-to-register-systemdb-database-to-cockpit-du.html

I would appreciate a root cause analysis and simple workaround without digging into Linux shell scripts and fixing installation .sh scripts developer typos. 

P.S. Previous versions of HANA 1.0 Express editions installations on VM passed as a breeze, so somebody should draw conclusions from mistakes.

**Comment by JCurrie27** [comment] 2018-05-28 11:12
Thanks for the feedback regarding your error messages during installation - I've asked the team to investigate. I'm not receiving these certificate-related errors when I perform the same installation on my laptop so we may need some details from you regarding your machine etc. to reproduce this issue.

**Comment by Lsubatin** [comment] 2018-05-28 14:36
@JCurrie27 I am also addressing this in the Q&A as a moderator (where it belongs).  Unfortunately, there is also not enough information there either, but there is the added component that it is running on Fusion Pro 10: https://answers.sap.com/questions/528948/tls-certificate-validation-failed-during-sap-hana.html?childToView=530021#comment-530021

**Comment by vsenn** [comment] 2018-05-28 15:04
Hi John and Lucia! 
Thank you for stepped in on to this issue. After a few days of trial and fail with installation on MacBooks Pro 16Gb I finally did it, but wouldn't recommend to install HANA SPS03 12GB VM to anyone  with 16Gg RAM. Nevertheless I finally got so cherished "Congratulations! SAP HANA, express edition 2.0 is configured." and free 4.1Gb on the HXE virtual server it quickly turned on to a complete headache during development tutorials for XSA. 

Continues build errors, websocket errors, gateway timeout URI and out of memory (running hxe_gc.sh after every build or step is not a way to go). I've turned off telemetry service but it didn't much help either. I'll try with stopped HXE database now, but don't expect a magic Eldorado.
If you have any other suggestions how to optimise HXE for less consumption of RAM I would appreciate that.

Regarding the issue: please specify in the install tutorial that ALL firewalls has to be completely switched OFF. Not only corporate networks but local home private networks and especially MacBook's internal one! This was a root cause o UAA authorisations and timeout issues during installation due to massive internal ports bombing in install procedure. I would suggest adding a port check in the beginning of the install procedure for the future, but this is just an idea..

**Comment by Lsubatin** [comment] 2018-05-28 15:26
Hi, Valery, 

I really like the suggestion on the ports check and the IPv4 being assigned too. Thanks for that.

I think this does not work on Mac but you can try: In my 16GB machine, I set the RAM in the VM to 24, but I know the swapping will happen on an SSD disk, an HDD will cause timeouts. I am also very careful not to be running other apps on my host machine, as that leaves very little real RAM for the VM.

I also scale di-core and di-runner to use 512M (command xs scale), stop the cockpit apps and disable telemetry.  That solves most of the errors from Web IDE timing out. However, this needs an additional half GB that you need to take from somewhere else **before** you scale (make sure the swapping works). This process can also take a while and interrupting it is not a good idea. 

If you are not using the tenant database (the XSA end to end tutorials do not need it, for example), you can also stop it or delete and that will free up more RAM.  It all depends on what you want to do.

If you need more functionality, like SDS or are planning on some heavy advanced analytics, then the cloud options are your friends (you are very likely to get 300USD credit from GCP when you first sign up so you can run the machine for free for a while - remember to HDB stop before you turn the VM off to avoid errors). 

This sizing guide gives you an idea of the consumption of each service: https://help.sap.com/viewer/9e4243e92f244537b2164a57a405a9fd/2.0.02/en-US 

hope this helps, 

Lucia.

**Comment by vsenn** [comment] 2018-05-28 17:27
Lucia, thank you for inside tips on performance! 
I'll definitely scale on di-core and di-runner and probably di-local-npm-registry also, as I've just got 
> (DIBuild) npm ERR! This is an error with npm itself.
> 
at Node.js build and I'd like to sacrifice on cockpit services and hdbsql instead. 

Could you advise what cockpit apps can be safely stopped and started only on demand during tutorials. I'd love to get this 2.5Gb back from cockpit for my business data!
xsa-cockpit              STARTED  1/1  256 MB
cockpit-persistence-svc  STARTED  1/1  768 MB
cockpit-hdb-svc          STARTED  1/1  768 MB
cockpit-xsa-svc          STARTED  1/1  768 MB
cockpit-collection-svc   STARTED  1/1  768 MB
cockpit-hdbui-svc        STARTED  1/1  128 MB
cockpit-landscape-svc    STARTED  1/1  128 MB
cockpit-web-app          STARTED  1/1  512 MB
cockpit-adminui-svc      STARTED  1/1  128 MB
cockpit-admin-web-app    STARTED  1/1  128 MB

P.S. I understand that this tread is off top in this context so maybe you can tell me where we can discuss further and this issue can be closed.

**Comment by thecodester** [comment] 2018-05-29 09:04
I am closing the issue since it looks like it is resolved. Feel free to reopen or continue the conversation.

**Closed by thecodester** 2018-05-29 09:04 UTC
