### ISSUE TITLE
Build and Deploy an SAP Web IDE Extension (MTA Project)

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#4917] opened 2020-04-10 09:51 UTC
Tutorial URL: https://developers.sap.com/tutorials/webide-extension-build.html

Please specify the step you are referring to

Step 2: Deploy your extension to SAP Cloud Platform

I try and deploy the mtar file to SAP Cloud Platform and it states it is deployed however I cannot find this application in the list of applications.

7:47:24 PM (DeployService) Target: https://deploy-service.cfapps.eu10.hana.ondemand.com/slprot/P028445trial_trial/dev/slpPreparing to deploy /myproject/mta_archives/myextension_0.0.1.mtarPrepare deployment filesChecking if there are conflicting processesFound 0 conflicting processesUploading mtar archiveStarting deploymentDeploying in org "P028445trial_trial" and space "dev"Detected MTA schema version: "3"Detected deployed MTA with ID "myextension" and version "0.0.1"Detected new MTA version: "0.0.1"Deployed MTA version: "0.0.1"Updating application "myproject"...Application "myproject" attributes are not modified and will not be updatedUploading application "myproject"...Publishing publicly provided dependency "myextension:myproject"...Deleting discontinued configuration entries for application "myproject"...Skipping deletion of services, because the command line option "--delete-services" is not specified.To download the process logs, use the "cf dmol -i 38e7f408-7b10-11ea-8a70-eeee0a9dffeb" command in the Cloud Foundry CLI directly in your Cloud Foundry space.See https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e93b231895b64cbc9221a62953563a6f.html.Job finished successfully.
7:47:24 PM (DeploymentToCF) Could not fetch information for myextension
7:47:24 PM (DeploymentToCF) The "myextension" project has been deployed.

 I go to my space but don't see the application listed. 

Please assist.

Thanks & Kind Regards
Phil Cooley

**Comment by thecodester** [comment] 2020-06-25 10:51
@Paolaufer  You can just write a note asking @katunin-ng to look into it, but the assignee is always the author.

**Comment by thecodester** [comment] 2020-06-30 06:53
@idogoren can you help here?

**Comment by idogoren** [comment] 2020-07-02 09:18
@pjcools - I've tried to reproduce the scenario and both build and deploy worked for me.
Once the deploy step was done, I've navigated to my space in the Cockpit and saw the deployed application.
Unfortunately, I didn't manage to reproduce your issue.

**Comment by MichaelCzcz** [comment] 2020-07-21 11:07
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-07-21 11:07 UTC
