### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by mconvertino** [SAPDocuments/Tutorials#5252] opened 2020-06-02 20:13 UTC
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-webide-int.html

I have followed all the Tutorials of the Group "Get Started with SAP API Management", but I am facing an Issue in this tutorial as my Web IDE is giving me an error instead of the message shown in step 14 after selecting the API Product  
<img width="725" alt="2020-06-02 22_07_06-SAP Web IDE Full-Stack" src="https://user-images.githubusercontent.com/55501964/83565036-f5852600-a51d-11ea-9c60-c24e1720cdff.png">

How do I solve the problem?

Thanks and regards,
Matteo

**Comment by thecodester** [comment] 2020-06-04 07:31
@shilpavij Can you take a look at this? If this tutorial is no longer up to date or needed, let us know? If so, what better tutorial is there?

**Comment by shilpavij** [comment] 2020-06-04 08:17
Dear team,

Let me check with the Product team if there are changes, will get back.

Regards
Shilpa

**Comment by shilpavij** [comment] 2020-06-04 08:47
Dear All,

There is a bug and team is fixing it. Kindly wait for the fix.

Regards
Shilpa

**Comment by shilpavij** [comment] 2020-06-04 08:57
Dear All,

The document is updated and there is no problem with it. There is a regression bug and the team is fixing it.

Regards
Shilpa

**Comment by thecodester** [comment] 2020-06-07 07:15
@shilpavij do you have an estimate on when it will be fixed?

**Comment by shilpavij** [comment] 2020-07-21 09:25
It is fixed now. Kindly check.

**Comment by MichaelCzcz** [comment] 2020-07-21 09:26
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-07-21 09:26 UTC
