### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by AmauryVanEspen** [SAPDocuments/Tutorials#5027] opened 2020-04-27 12:32 UTC
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Step 3: missing module @sap/hana-client to run my_bookshop-srv

see log

`   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR [ERROR] Cannot find module '@sap/hana-client'
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at Module.require (internal/modules/cjs/loader.js:692:17)
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at require (internal/modules/cjs/helpers.js:25:18)
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at _getClient (/home/vcap/deps/0/node_modules/@sap/cds-hana/lib/client/hanaClient.js:7:36)
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/deps/0/node_modules/@sap/cds-hana/lib/client/hanaClient.js:18:18)
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at Module._compile (internal/modules/cjs/loader.js:778:30)
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at Module.load (internal/modules/cjs/loader.js:653:32)
   2020-04-27T14:28:19.15+0200 [APP/PROC/WEB/0] ERR     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
   2020-04-27T14:28:19.25+0200 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
   2020-04-27T14:28:19.34+0200 [APP/PROC/WEB/0] ERR npm ERR! errno 1
   2020-04-27T14:28:19.34+0200 [APP/PROC/WEB/0] ERR npm ERR! my_bookshop@1.0.0 start: `npx cds run`
   2020-04-27T14:28:19.34+0200 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
   2020-04-27T14:28:19.34+0200 [APP/PROC/WEB/0] ERR npm ERR!
   2020-04-27T14:28:19.34+0200 [APP/PROC/WEB/0] ERR npm ERR! Failed at the my_bookshop@1.0.0 start script.
   2020-04-27T14:28:19.34+0200 [APP/PROC/WEB/0] ERR npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
   2020-04-27T14:28:19.35+0200 [APP/PROC/WEB/0] ERR npm ERR! A complete log of this run can be found in:
   2020-04-27T14:28:19.36+0200 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/.npm/_logs/2020-04-27T12_28_19_349Z-debug.log`

**Comment by chgeo** [comment] 2020-04-28 14:20
Thanks for reporting
@iwonahahn Please close this as a duplicate of #5036

**Comment by iwonahahn** [comment] 2020-04-28 14:26
@thecodester can you please close the issue?

**Closed** 2020-04-28 15:17 UTC
