### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by alvinrinaldy** [SAPDocuments/Tutorials#5358] opened 2020-06-24 06:52 UTC
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to

While entering password and try to login, there is little message under the column said "btoa is not defined"
![image](https://user-images.githubusercontent.com/30219123/85510716-f6dbd700-b621-11ea-84c7-e0bd6655ad1d.png)

**Comment by theStiggySpd** [comment] 2020-06-24 16:07
Hi @alvinrinaldy  
Can you please use the service URL and try in a browser? Enter your credentials. Does it return a valid metadata document for you?

**Comment by alvinrinaldy** [comment] 2020-06-24 16:17
Hi @theStiggySpd 

Here is the snapshot when I access the service URL.
![image](https://user-images.githubusercontent.com/30219123/85592876-beafb500-b670-11ea-85c3-d9c7c5aeef20.png)


I think this one is valid enough for me.

**Comment by theStiggySpd** [comment] 2020-06-24 16:27
thanks for checking @alvinrinaldy  
Just to confirm, you cannot log in and goto next step, right?
If you are blocked, do you mind if I ask you to create an incident for me in BCP component "CA-UX-IDE"

**Comment by alvinrinaldy** [comment] 2020-06-24 16:37
Hi @theStiggySpd ,

could you please share how to do that. Because I am kinda new to the incident stuff, from launchpad.support.sap.com I am stuck on this screen.
![image](https://user-images.githubusercontent.com/30219123/85596093-a42b0b00-b673-11ea-9be4-abafc70c95f8.png)

Reference: https://blogs.sap.com/2016/06/29/how-to-create-sap-support-incident-legacy-name-oss-support-message/

**Comment by SanderStar** [comment] 2020-07-01 08:13
I have the same issue.

**Comment by SanderStar** [comment] 2020-07-01 09:07
Generate the app with a local metadata file.
Request metadata file https://sapes5.sapdevcenter.com/sap/opu/odata/sap/SEPMRA_PROD_MAN/$metadata
Save the metadata file on your local computer
Browse in the generation proces to the local file
Start the app with npm run start-mock

**Comment by SanderStar** [comment] 2020-07-01 11:27
Or use another odata service: https://services.odata.org/V2/Northwind/Northwind.svc

**Comment by juanfelipe82193** [comment] 2020-07-01 14:54
Looking forward to see how this issue can be fixed.

Regards.

Juan.

**Comment by ianquigley-sap** [comment] 2020-07-02 10:02
Thanks @alvinrinaldy we are now actively looking into resolving this issue.

**Comment by ianquigley-sap** [comment] 2020-07-02 14:59
@alvinrinaldy we are having trouble recreating this issue locally.  Would you be able to reach out to me please and we can have a conversation about it? My email is ian.quigley@sap.com

Thanks.

**Comment by sanjoy0308** [comment] 2020-07-03 10:18
I am also facing same issue. 
@ianquigley-sap , I can help you recreating this issue. I can share my screen to show you the issue if you want.

**Comment by ianquigley-sap** [comment] 2020-07-03 12:44
Great, thank you @sanjoy0308 .  I will reach out to you to setup a meeting.

**Comment by ianquigley-sap** [comment] 2020-07-03 13:58
@sanjoy0308 can you please email me at ian.quigley@sap.com so that I can set up a follow up meeting with you?  Thanks

**Comment by sanjoy0308** [comment] 2020-07-03 14:13
@ianquigley-sap I have sent you an email. Thank you.

**Comment by alvinrinaldy** [comment] 2020-07-03 19:33
Hi @sanjoy0308 , Thanks for your help to provide re-create the issue. I am kinda distracted from this issue because of other work. lets look forward to see how this issue can be fixed.
If you need me to join the discussion, hit me on alvin.rinaldy07@gmail.com. 

Thank you.

**Comment by sanjoy0308** [comment] 2020-07-03 22:15
@ianquigley-sap , I am now able to connect to ES5, but I am facing same problem when I am connecting to my xsodata. Can I show you that issue, please?

**Comment by juanfelipe82193** [comment] 2020-07-03 22:18
Hi @sanjoy0308 how did you fix the btoa issue? Thanks in advance

**Comment by sanjoy0308** [comment] 2020-07-04 04:36
I used SAP Business Application Studio, then it works. I was trying in my vs code earlier.

**Comment by juanfelipe82193** [comment] 2020-07-04 13:22
Yeah, I could finish the turorial with Business Application Studio too. But I’d really like to make it work with VS.

Thank you!

**Comment by theStiggySpd** [comment] 2020-07-06 06:01
Hi all, thanks for your active help in recreating this issue and meanwhile also trying the tutorial on Business Application Studio.
I hope we can reproduce this issue and release a fix asap.

**Comment by MichaelCzcz** [comment] 2020-07-09 07:52
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-07-09 07:52 UTC

**Comment by juanfelipe82193** [comment] 2020-07-09 13:17
Hi, Michael. So the resolution will be to use Business Application Studio instead of VS Code?

**Comment by ianquigley-sap** [comment] 2020-07-09 13:30
Hi, we are still actively investigating the issue with @sanjoy0308.  It looks like a third party library used has a dependency that is only causing issues on some landscapes.  It is still under investigation.

**Comment by ianquigley-sap** [comment] 2020-07-14 10:27
We have identified the issue after discussions with @sanjoy0308.  It looks like another VSCode extension from SAP is causing this error with the generator.  As a workaround, please check if you have the `mobile Development Kit extension for Visual Studio Code` installed:

![image](https://user-images.githubusercontent.com/15449680/87415299-d40b6580-c5c4-11ea-8f58-8975d09a0ffa.png)

If it is, please disable it before running the generator. That should resolve the `BTOA` error.

**Comment by SanderStar** [comment] 2020-07-14 10:33
Yes, that is the solution in my case. Now it works.

**Comment by juanfelipe82193** [comment] 2020-07-14 13:25
Yes, it is working now without problem. Even the generator is showing also UI5 apps option.

Thank you so much!

**Comment by marcellourbani** [comment] 2020-09-23 08:07
AFAIK btoa is defined in browsers but not in nodejs.
How that bit of code gets to run in node beats me

**Comment by ivanlynch** [comment] 2020-10-31 12:15
> We have identified the issue after discussions with @sanjoy0308. It looks like another VSCode extension from SAP is causing this error with the generator. As a workaround, please check if you have the `mobile Development Kit extension for Visual Studio Code` installed:
> 
> ![image](https://user-images.githubusercontent.com/15449680/87415299-d40b6580-c5c4-11ea-8f58-8975d09a0ffa.png)
> 
> If it is, please disable it before running the generator. That should resolve the `BTOA` error.

I did it and now VSCode is working, thanks!
