### ISSUE TITLE
sapcpsdk-proxygenerator Code compilation failed

### ISSUE THREAD

**Issue by agiguere** [SAPDocuments/Tutorials#2172] opened 2018-01-10 16:51 UTC
I am starting learning the new SDK for iOS but where should we log bugs ??

Right now I can't generate proxy classes using the sapcpsdk-proxygenerator CLI

it says Code compilation failed Missing semicolon before 'return'.

my service document metadata comes from Gateway SAP_GWFND 740	0014

please help

thanks

**Comment by qualiture** [comment] 2018-01-15 10:08
Hi @agiguere,

Can you check whether sapcpsdk-proxygenerator works with for instance the Northwind OData service (http://services.odata.org/V2/Northwind/Northwind.svc/) or the Sample OData service included in SAPcpms?

**Comment by agiguere** [comment] 2018-01-15 14:04
hi, yes I could give it a try, but I tried another service metadata from our backend and it was working so I don't know why for a particular one it failed. Is there a way to submit you the file for error investigation, I find it difficult to find support around this product.

**Comment by qualiture** [comment] 2018-01-15 16:40
Hi @agiguere,

Unfortunately, this repository and it's logged issues are for the tutorials only -- any issues with the tools itself should be logged using different channels.

The SDK Assistant has an option to report an issue; in the application's top-menu, choose **Help > Report an issue**.

Alternatively, you could log on to the [SAP Support Portal](https://support.sap.com/en/index.html), choose **Report an Issue**, and enter a search term for your issue, for instance `iOS sdk proxy`. 

I did a search and it seems the issue is not yet identified, so after you did a KBA search, only then the **Submit an Incident** button is visible

**Comment by agiguere** [comment] 2018-01-15 16:57
thanks, but that's the problem with this iOS SDK assistant,

I have seen the option in the menu to report a bug and it brings us to the support page,

if I use my personnel user (S*) it says missing authorization

if I use my company user (we are partner), I need to select a customer, system etc ...

this is totally not related, I just want to submit a bug for the iOS assistant

I am not sure how you want the community to report bugs for this product if the SCP trial landscape users does not have sufficient authorization to report incidents

alex

thanks

**Comment by qualiture** [comment] 2018-01-15 17:07
@agiguere I tried it myself and was stuck too -- yeah, this is genuinely annoying :( 

I have contacted the development team and asked for a more streamlined & less enterprisey way for trial users to report bugs.

I'll update once I know more -- keep you posted!

**Comment by agiguere** [comment] 2018-01-15 17:12
thanks for the help, even for enterprise,

let say I am doing a POC for a potential new client, when I go to the support portal and log with my SAP Partner ID, I will have to select the customer, system etc ... but we have not sold it yet (SCPms) so the system won't be there in the dropdown list ...

Alex

**Comment by qualiture** [comment] 2018-01-15 17:17
True, as the current approach also bypasses the whole concept of a "trial"... 

I wholeheartedly agree the current issue reporting process is not feasible, viable and desirable for trial users, but I don't know if the team has a simple solution à la OpenUI5 bug reporting in place yet... I'll keep you posted

**Comment by qualiture** [comment] 2018-01-15 17:27
Hi @agiguere 

The answer I got was:

> Unfortunately there’s no better way that I’m aware of. I’ve tried getting to a GitHub account for this, but no avail so far. The answers.sap.com is the only place if you’re not a customer who can file BCP tickets

So unfortunately, as of yet there isn't anything in place other than answers.sap.com, but I'll try to raise this topic as it affects other trial users (HANA Express Edition, Cloud Platform, etc) as well. Right now, these two examples also direct non-customers to SCN too...

**Comment by agiguere** [comment] 2018-01-15 18:19
ok thanks, while we are here, I was testing the logUploader with my trial account and I got this error in SCPms

I generate a new iOS app with the Assistant and enable logging

in my AppDelegate I added these line to push log to SCPms

```
    func application(_: UIApplication, didFinishLaunchingWithOptions _: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        if let parent = logger.parent {
            let documentURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
            
            let logFileURL = documentURL.appendingPathComponent("LogFile.log")
            
            parent.logLevel = .error
            parent.add(handler: ConsoleLogHandler())
            
            do {
                try parent.add(handler: FileLogHandler(fileURL: logFileURL))
                
            } catch {
                print(error)
            }
        }
```

I can see the log file is generated correctly and the log are submitted to SCP but in SCPms Analysis --> Log I have this error

The uploaded client log could not be parsed. A log line must start and end with the character '#'.

any idea?

thanks

**Comment by qualiture** [comment] 2018-01-16 05:40
Hi,

I will forward this to the development team

**Comment by qualiture** [comment] 2018-01-16 11:22
Hi @agiguere,

In mobile services cockpit at Analysis->Logs or ->Events, is there maybe an error with more information?

If not, can you maybe provide your SAP CP account so the server team can look into it

**Comment by agiguere** [comment] 2018-01-16 17:24
sure thanks, how do you want to proceed?

I can see it's for component Registration

**Comment by qualiture** [comment] 2018-01-17 10:22
Maybe better to take this via a different channel -- sent you a LI invite

**Comment by thecodester** [comment] 2018-02-11 09:30
Thank you for your feedback. The issue seems to be resolved (or taken offline), so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2018-02-11 09:30 UTC
