### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by MariusPlaceWorkers** [SAPDocuments/Tutorials#3208] opened 2019-03-13 15:50 UTC
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsjs-xsodata.html

I do not now at which point of the tutorial i make a mistake, so i can not speciefied the step.
When i try to run the node.js module in the end of the Tutorial i get an error 

MaxListenersExeceedWarning: Possible EventEmitter memory leak detetected. 11 message Listeners added. Use emitter.setMaxListeners() to increase limit.

When i now follow the link to the site then stand there Unauthorized

Can sombody help me out ?

**Comment by MariusPlaceWorkers** [comment] 2019-03-16 14:17
Okay i have fixed it. My problem was that i used the firefox browser instead of Chrome. In the Firefox was no Database explorer available. 

So if somone else got also problems try to use chrome and set the setting that the cerificate form your hana system is okay.

**Comment by thecodester** [comment] 2019-03-17 06:00
Thanks for the feedback. If the issue is resolved, please close the issue, thanks.

**Closed** 2019-03-17 17:32 UTC
