### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#5892] opened 2020-09-21 09:54 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Hi,

In step 6: we are not able to get the access to ‘Open Connector’ even though the status is active. It gives below error when we click on the URL to check if we have access to the capability or not. Even if we have added ‘OpenConnectors_User’ role to the user.
Error screenshot:
![image](https://user-images.githubusercontent.com/69286515/93752944-023c9f80-fc1d-11ea-9081-1d8ab7474ede.png)

Status and url screenshot:
![image](https://user-images.githubusercontent.com/69286515/93753001-1d0f1400-fc1d-11ea-85b1-9b142aa37abb.png)

Added roles screenshot:
![image](https://user-images.githubusercontent.com/69286515/93753428-c48c4680-fc1d-11ea-8163-356ef9b8c716.png)

Please tell how we can solve this issue.

Labels:
Landscape label: trail1
Scenario Label: SCPTest-cloudin

Regards,
Akanksha

**Comment by Vikramkulkarni01** [comment] 2020-09-22 03:59
Hi @AkankshaKullu , 
Once you activate the capabilities and assign the roles. Please perform the following task. 

1. Reload the pa
2. Log out and login back. 

Let me know if you are still facing any issues. 

Regards,
Vikram Kulkarni

**Comment by AkankshaKullu** [comment] 2020-09-23 09:48
Hi @Vikramkulkarni01,

The proposed steps has been performed still not able to access 'Open connector' getting the below error
![image](https://user-images.githubusercontent.com/69286515/93996443-e1f11a00-fdaf-11ea-9c21-15a0a14c5e44.png)

The url : https://api.openconnectors.trial.eu10.ext.hana.ondemand.com/elements/api-v2/authentication/saml/105/assert

Please tell what can be done.

Regards,
Akanksha

**Comment by Vikramkulkarni01** [comment] 2020-11-09 08:49
Hi @AkankshaKullu , 
The issue seems to be resolved now. I checked in my trial account and I cannot able to reproduce the issue. 

Please check

**Comment by MichaelCzcz** [comment] 2020-11-09 08:57
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-11-09 08:57 UTC
Labels: SCPTest-2008A, SCPTest-cloudin, SCPTest-trial1
