### ISSUE TITLE
Install the Optional SAP HANA Automated Predictive Library Package for SAP HANA, express edition (Native Linux Machine)

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#3831] opened 2019-08-26 18:59 UTC
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-apl-binary.html

Step 1, when trying to run `HXEDownloadManager_linux.bin`, I receive the error seen below (Using HXE Docker 2.4):

```bash
hxeadm@hxe:/usr/sap/HXE/home> ls -lart
total 64
drwx------ 2 hxeadm sapsys 4096 Sep 21  2014 .local
drwxr-xr-x 2 hxeadm sapsys 4096 Sep 21  2014 .fonts
drwx------ 2 hxeadm sapsys 4096 Sep 21  2014 .config
-rw-r--r-- 1 hxeadm sapsys 6043 Aug 19  2016 .muttrc
-r-xr-xr-x 1 hxeadm sapsys  159 Mar  1 09:16 .sapsrc.sh
-r-xr-xr-x 1 hxeadm sapsys  176 Mar  1 09:16 .sapsrc.csh
-r-xr-xr-x 1 hxeadm sapsys 1791 Mar  1 09:16 .profile
-r-xr-xr-x 1 hxeadm sapsys 2495 Mar  1 09:16 .cshrc
-r-xr-xr-x 1 hxeadm sapsys 2256 Mar  1 09:16 .bashrc
-rwxr-x--- 1 hxeadm sapsys 3021 Jul 30 00:40 .sapenv.sh
-rwxr-x--- 1 hxeadm sapsys 2986 Jul 30 00:40 .sapenv.csh
drwxr-xr-x 4 hxeadm sapsys 4096 Jul 30 00:40 ..
drwxr-xr-x 6 hxeadm sapsys 4096 Jul 30 00:40 .
-rw------- 1 hxeadm sapsys   50 Jul 30 00:41 .bash_history
drwxr-xr-x 2 hxeadm sapsys 4096 Jul 30 00:41 bin
hxeadm@hxe:/usr/sap/HXE/home> cd bin/
hxeadm@hxe:/usr/sap/HXE/home/bin> ls
HXECheckUpdate_linux.bin  HXEDownloadManager_linux.bin  change_key.sh  hxe_gc.sh
hxeadm@hxe:/usr/sap/HXE/home/bin> ./HXEDownloadManager_linux.bin linuxx86_64 installer apl.tgz
which: no java in (/usr/sap/HXE/HDB90/exe/krb5/bin:/usr/sap/HXE/HDB90/exe/krb5/sbin:/usr/sap/HXE/HDB90/hxe:/usr/sap/HXE/HDB90:/usr/sap/HXE/HDB90/exe:/usr/sap/HXE/HDB90/exe/mdc:/usr/sap/HXE/HDB90/exe/Python/bin:/usr/sap/HXE/HDB90/exe/dat_bin_dir:/usr/sap/HXE/home:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
which: no java in (/usr/sap/HXE/HDB90/exe/krb5/bin:/usr/sap/HXE/HDB90/exe/krb5/sbin:/usr/sap/HXE/HDB90/hxe:/usr/sap/HXE/HDB90:/usr/sap/HXE/HDB90/exe:/usr/sap/HXE/HDB90/exe/mdc:/usr/sap/HXE/HDB90/exe/Python/bin:/usr/sap/HXE/HDB90/exe/dat_bin_dir:/usr/sap/HXE/home:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
This program is generated by unregistered Jar2Exe and it has expired to run for DEMO use.
```

**Comment by entmike** [comment] 2019-09-09 14:13
Just an FYI - Someone is now complaining about this on the SAP forums:

https://answers.sap.com/questions/12857573/hxecheckupdatejar-jar2exe-has-expired.html

**Comment by Lsubatin** [comment] 2019-09-09 14:17
Thanks, Mike. Engineering is working on it

**Comment by gschukat** [comment] 2019-11-13 10:23
> Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-apl-binary.html
> 
> Step 1, when trying to run `HXEDownloadManager_linux.bin`, I receive the error seen below (Using HXE Docker 2.4):
> 
> ```shell
> hxeadm@hxe:/usr/sap/HXE/home> ls -lart
> total 64
> drwx------ 2 hxeadm sapsys 4096 Sep 21  2014 .local
> drwxr-xr-x 2 hxeadm sapsys 4096 Sep 21  2014 .fonts
> drwx------ 2 hxeadm sapsys 4096 Sep 21  2014 .config
> -rw-r--r-- 1 hxeadm sapsys 6043 Aug 19  2016 .muttrc
> -r-xr-xr-x 1 hxeadm sapsys  159 Mar  1 09:16 .sapsrc.sh
> -r-xr-xr-x 1 hxeadm sapsys  176 Mar  1 09:16 .sapsrc.csh
> -r-xr-xr-x 1 hxeadm sapsys 1791 Mar  1 09:16 .profile
> -r-xr-xr-x 1 hxeadm sapsys 2495 Mar  1 09:16 .cshrc
> -r-xr-xr-x 1 hxeadm sapsys 2256 Mar  1 09:16 .bashrc
> -rwxr-x--- 1 hxeadm sapsys 3021 Jul 30 00:40 .sapenv.sh
> -rwxr-x--- 1 hxeadm sapsys 2986 Jul 30 00:40 .sapenv.csh
> drwxr-xr-x 4 hxeadm sapsys 4096 Jul 30 00:40 ..
> drwxr-xr-x 6 hxeadm sapsys 4096 Jul 30 00:40 .
> -rw------- 1 hxeadm sapsys   50 Jul 30 00:41 .bash_history
> drwxr-xr-x 2 hxeadm sapsys 4096 Jul 30 00:41 bin
> hxeadm@hxe:/usr/sap/HXE/home> cd bin/
> hxeadm@hxe:/usr/sap/HXE/home/bin> ls
> HXECheckUpdate_linux.bin  HXEDownloadManager_linux.bin  change_key.sh  hxe_gc.sh
> hxeadm@hxe:/usr/sap/HXE/home/bin> ./HXEDownloadManager_linux.bin linuxx86_64 installer apl.tgz
> which: no java in (/usr/sap/HXE/HDB90/exe/krb5/bin:/usr/sap/HXE/HDB90/exe/krb5/sbin:/usr/sap/HXE/HDB90/hxe:/usr/sap/HXE/HDB90:/usr/sap/HXE/HDB90/exe:/usr/sap/HXE/HDB90/exe/mdc:/usr/sap/HXE/HDB90/exe/Python/bin:/usr/sap/HXE/HDB90/exe/dat_bin_dir:/usr/sap/HXE/home:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
> which: no java in (/usr/sap/HXE/HDB90/exe/krb5/bin:/usr/sap/HXE/HDB90/exe/krb5/sbin:/usr/sap/HXE/HDB90/hxe:/usr/sap/HXE/HDB90:/usr/sap/HXE/HDB90/exe:/usr/sap/HXE/HDB90/exe/mdc:/usr/sap/HXE/HDB90/exe/Python/bin:/usr/sap/HXE/HDB90/exe/dat_bin_dir:/usr/sap/HXE/home:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
> This program is generated by unregistered Jar2Exe and it has expired to run for DEMO use.
> ```

the download can be run easily with the downloader `jar` if some `java` is installed, instead of the executable:

```shell
java -jar HXEDownloadManager.jar -d ./ztmp linuxx86_64 installer apl.tgz 
Connecting to download server...

SAP HANA, express edition version: 2.00.040.00.20190729.1

Downloading "SAP HANA Automated Predictive Library"...
apl.tgz : 100%
Concatenate download files to ./ztmp/apl.tgz...
./ztmp/apl.tgz created.
Verify ./ztmp/apl.tgz file checksum...
./ztmp/apl.tgz file checksum is OK.
```  
`HXEDownloadManager.jar` is available where `HXEDownloadManager_linux.bin` can be found.

but that does not help with the updater, as there is no `jar` available, only `/usr/sap/HXE/home/bin/HXECheckUpdate_linux.bin`  

Any progress with the updater?

**Comment by LarsBr** [comment] 2019-11-18 08:21
This issue indeed looks like as it has been dropped... has anyone taken over Lucia's work after she left SAP?

**Comment by thecodester** [comment] 2019-11-19 11:51
@rbrainey Can you help here?

**Comment by gitjbz** [comment] 2019-12-09 09:33
As per [this answer on SAP support] (https://answers.sap.com/questions/12857573/hxecheckupdatelinuxbin----jar2exe-has-expired.html)
you need to first reset the systemdate, because apparently the bin was built with a demo-version and has already exipered...
`sudo timedatectl set-time 2019-07-31`
after that, invoke the `HXEDownloadManager_linux.bin` command.

**Comment by LarsBr** [comment] 2019-12-10 01:12
Ok, this does not look right.

First off, changing the local time/date back to when the demo license for the `[Jar2Exe](https://jar2exe.com/)` tool was still valid is a breach of the license agreement.

It's not simply cheating and therefore bad in a moral sense but depending on jurisdiction illegal.

The fact that this "solution" was offered on an SAP support site makes it look as if SAP is endorsing this. 
While the fine-print for SAP Community makes it clear, that SAP is not liable for the stuff people post on the user forum, the fact that SAP packages up and delivers a time-limited demo software and let's a "solution" stand uncommented/unmoderated that basically leads to a license breach is not a good look (at the very least).

Looking further into the [Jar2Exe license](https://jar2exe.com/sites/jar2exe/files/License_Agreement.pdf) agreements, the packaging of the demo-software is problematic further. SAP explicitly allows and advertises the **productive** use of the SAP HANA Express Edition for memory configurations up to 32GB.  
The Jar2Exe license, however, explicitly only allows that executable binary files created with the demo license to be used for **testing and evaluation** purposes.

The kicker is that the "**biggest**" license (the one that allows for productive usage within a workgroup, e.g. the team that releases the _HXECheckUpdate_linux_ and _HXEDownloadManager_ tools) for Jar2Exe costs just US$145. 
At that price, somebody in that team should have considered whether just buying that tool would not be the right idea or if the tool is required at all.

**Comment by gitjbz** [comment] 2019-12-11 09:31
Totally agree with you Lars, concerning the bad morality of the solution, but hey, we're trying to get the Express Edition and some of the addons running.

As this is currently the only available working solution, we just have to live with the fact that we're kinda cheating.

Unless ofcourse you can convince your SAP-collegues in de HXE-development team to purchase the jar2exe license ;-)

**Comment by LarsBr** [comment] 2019-12-12 02:12
Ha! I would love to do that, but the SAP-colleagues are my **former** SAP-colleagues (I left the company a while ago) and I really don't have a "private line" to them.

**Comment by mathsen** [comment] 2019-12-17 22:55
I really can understand why everybody who is being asked to help here left the company.
It's such a big shame, that this problem is still not fixed yet.

**Comment by Lsubatin** [comment] 2019-12-18 03:32
**Disclaimer: I'm not an SAP employee any more and I'm done with that community, but this thing with the dates is hitting rock bottom.** 

You can download a working version of HXEDownloadManager_linux.bin from the download page and upload it into your VM. No need to get shady with the dates. 

1. Go here: https://www.sap.com/cmp/td/sap-hana-express-edition.html?infl=3d6178c3-dded-49c7-b799-32726fc8f17d - Follow the reg process 
2. Choose "Linux DM" in the toast that says " Get the Download Manager (DM) for SAP HANA 2.0, express edition below." This should be easier than the JRE one, but pretty much the same and you can get that one from this toast too.
![image](https://user-images.githubusercontent.com/24896969/71052730-4c3aa700-211a-11ea-8020-da7907ca837b.png)

3. Upload the .bin file into the VM. Grant permissions to execute and run 

![image](https://user-images.githubusercontent.com/24896969/71052952-ebf83500-211a-11ea-81e5-7cae31ea5011.png)

As for the update checker, if you only want to see if a new version is out, I'd check the HXE site where releases are posted together when an update is released - this used to happen with a couple of hours of difference: https://developers.sap.com/topics/sap-hana.html#releaseNotes . You could also use the same downloader with a non-existent target directory and you'll get the date of the last update from there too. 

![image](https://user-images.githubusercontent.com/24896969/71053331-21e9e900-211c-11ea-9394-ba583713da56.png)

I'm not saying this is good or convenient or anything, just better than the dates "hack".

**Comment by entmike** [comment] 2020-01-07 16:27
I've also taken a similar approach as @Lsubatin -- Just copy the binary from the VM image.  Does it work?  Yes.  Is it silly and annoying?  Also yes.  Is this surprising given that it's SAP?  No.

PS - This technique (borrowing files from VM image) is also how I brought XS Classic delivery units into my HXE docker container.  It also works with a bit of elbow grease.

https://github.com/entmike/hana-dpagent/blob/master/BootstrappingHXE.md

**Comment by thecodester** [comment] 2020-01-08 06:46
Thank you for your feedback. The issue seems to be resolved (however not perfect it is), so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

FYI to @jung-thomas @JCurrie27

**Closed by thecodester** 2020-01-08 06:46 UTC

**Comment by mathsen** [comment] 2020-01-08 06:49
@thecodester please tell me, that some SAP guy really fixed the root of the problem and that you don't close the issue because of some really *nasty* workaround... Otherwise I really loose my last trust into SAP...

**Comment by thecodester** [comment] 2020-01-08 07:05
I'm sorry for your frustration. I meant to close the issue here because (a) it seems the issue is technically not about the tutorial but the product, and this forum is about the tutorials; (b) a question is already opened in the SAP Community (see above).

But of course the discussion can continue here, and we can provide more information when it is available.
