### ISSUE TITLE
Add Routing to a UI5 Web Components for React Project

### ISSUE THREAD

**Issue by kumser0** [SAPDocuments/Tutorials#5869] opened 2020-09-16 07:00 UTC
Tutorial URL: https://developers.sap.com/tutorials/ui5-webcomponents-react-routing.html

My issue is not related directly to this guide, but it is rather a follow-up problem.
I created an app with React Router, same or similar as in this guide.
Now I would like to deploy it to Cloud Foundry. As far as I understand, the suggested way is to deploy it to HTML5 App Repository and serve it via application router (there are a couple of guides describing that).
However I could find no info regarding how to configure the application router properly, so that it can properly work with React Router and e.g. open the routes directly. Or to put it more general, what is the proposed approuter config for such a React app with react-router-dom?
As of now my config looks as below, which basically would always open the start page (by serving index.html), but it does not allow to directly open the route, e.g. `https://<app-router>/user` -> such a request will fail, however running locally with `http://localhost:3000/user` will route directly to the corresponding component. 
In my case I use BrowserRouter instead of HashRouter in React, but imagine the issue would be rather similar.

`xs-app.json`
```
{
    "welcomeFile": "index.html",
    "authenticationMethod": "route",
    "routes": [
        {
            "source": "^(/.*)",
            "target": "/<app.id>/$1",
            "service": "html5-apps-repo-rt",
            "authenticationType": "xsuaa"
        }
    ]
}
```

**Comment by MarcusNotheis** [comment] 2020-09-23 13:38
Hey @kumser0,

I'm not a cloud foundry expert but let me try to add my thoughts here.

### Usage of `BrowserRouter` vs `HashRouter`
Using the `BrowserRouter` instead of the `HashRouter` is actually making a difference in how the requests are handled by the HTML5 Application Repository. 
When using the `HashRouter`, you are always requesting the `index.html` because the route part if added as location hash, but is not part of the path: `https://<app-router>/index.html#/user` and every other route will be resolved to your index.html which would be the expected behavior.
When using the `BrowserRouter`, the HTML5 App Repository will try to resolve the path `https://<app-router>/user` to `/user/index.html` which is not existing. I tried to play around with the routes array to redirect all requests that are not part of the `create-react-app` `build` folder to the `index.html` but I had no success on that one.

### Possible Workaround

I saw a couple of applications solving the issue you are facing by using the `nodejs` buildpack and running an own express server which is always serving the index.html:
```js
const express = require('express');
const path = require('path');

const PORT = process.env.PORT || 3000;
const server = express();
const FRONTEND_BUILD = path.join(__dirname, 'build');

// start server
server.use(express.static(FRONTEND_BUILD));
server.get('/*', function(_, res) {
    res.sendFile(path.join(FRONTEND_BUILD, 'index.html'));
});
server.listen(PORT);
```
This would allow you to have every asset served from the build directory, and all unknown routes (e.g. `/user`) would be redirected to the index.html

**Comment by kumser0** [comment] 2020-09-29 07:57
Hi @MarcusNotheis , thank you for your detailed analysis!
If I understand you correctly, the last option you suggest will forward an unknown route to index.html, which means that it will not be possible to start the app other than on the home page (as all the other routes will not be recognised and forwarded to index.html). This would cause some usability issues, e.g. you start on home page, then navigate to `/user` and then you hit browser refresh, which brings you back to home. Is my summary / understanding correct?
What you mean with `HashRouter` vs `BrowserRouter` sounds promising, it looks like it would be possible to set up forwarding in the app router correctly. I will try it out, though I would also need to evaluate if switching to `HashRouter` will cause any issues for our app.

**Comment by MarcusNotheis** [comment] 2020-09-29 08:15
Hey @kumser0,

> This would cause some usability issues, e.g. you start on home page, then navigate to /user and then you hit browser refresh, which brings you back to home. Is my summary / understanding correct?

Not 100% percent. The `express` backend will answer any request to an unknown route with `index.html` - but the route in the browser would still be `/user`. This `/user` route will then be picked up by `react-router` (served via your `index.html`) and the router will then serve the corresponding page for `/user`.

**Comment by kumser0** [comment] 2020-09-29 14:19
@MarcusNotheis so this workaround solution means that I would bypass HTML5 App Repository service on CF completely, and in my app I write this server part serving the `build` static files, and in app router I route the request to this "frontend server" as a usual route, not as HTML5 Repo route?
Or do you mean that HTML5 App Repo part stays as-is and it rather must be done in the app router directly (by extending the "standard" app router behaviour)?

**Comment by MarcusNotheis** [comment] 2020-09-29 14:23
You would bypass the HTML5 App Repository completely as the express server will take care of serving your files. I guess @LuisValgoi can share more details on such a setup as he already has built such an application with UI5 Web Components for React on Cloud Foundry.

**Comment by kumser0** [comment] 2020-09-29 14:29
Ok, then it is clear so far I guess! We basically have two options: 1) switch to `HashRouter` or 2) switch to serving files with express server instead of HTML5 App Repo. 
I would explore both and see what fits best.
I guess you could also close this issue, as it was more about "theoretical" exploration of the options and we got it done!

**Comment by LuisValgoi** [comment] 2020-09-29 15:32
Hey All, 

Regarding the change from `HashR` to `BrowserR`, IMO, i think its necessary due the default behavior of exposing contents on a static build such React.

Regarding the `express` server mentioned by the Marcus, in deed its an alternative. In fact, this was the solution I have used to build and deploy an [React+UI5WebComponentsReact application](https://github.wdf.sap.corp/CloudSCAME/WEConnect-Frontend/commits/dev) into the CF.

But, there is another alternative [explained in this post here](https://blogs.sap.com/2019/06/03/cloudfoundryfun-5-play-asteroids-powered-by-react-secured-by-sap-cloud-platform/).

As we all know a guy 😆 , I know Maxim Kuul (maxim.kuul@sap.com) which also can contribute helping you on this other approach mentioned in the blog post.

**Comment by kumser0** [comment] 2020-09-30 07:32
Update: I switched from `BrowserRouter` to `HashRouter` in my app and it works fine with my app router config (using HTML5 App Repo). As I see no downside in `HashRouter` as of now, this most likely would be the way forward for us.
Thanks again for your support!

**Comment by MichaelCzcz** [comment] 2020-10-02 11:40
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-10-02 11:40 UTC
