### ISSUE TITLE
Create an Account on the Gateway Demo System

### ISSUE THREAD

**Issue by giovannidegani** [SAPDocuments/Tutorials#3120] opened 2019-02-20 13:36 UTC
Tutorial URL: https://developers.sap.com/tutorials/gateway-demo-signup.html

Please specify the step you are referring to

The tutorial is pointing to system registration of at https://register.sapdevcenter.com/

The certificate for that website has expired 11 days ago and is not accessible due to browser security

**Comment by giovannidegani** [comment] 2019-02-20 13:37
@JijoRoyJacob

**Comment by thecodester** [comment] 2019-02-20 13:55
@qmacro I've assigned to Jonathan but wanted to alert you in case your tutorials make use of this tutorial.

**Comment by jonathanbaker7** [comment] 2019-02-20 13:56
No, this is on our end.  The certificate expired, and I didn’t realize it.  I’ll fix it this morning.


J

**Comment by jonathanbaker7** [comment] 2019-02-20 14:10
The problem is not a bad certificate, but some kind of mis-configuration problem in the NEO environment.  I’ll try to resovle it.  If I can’t, I’ll escalate it to Jim Jaquet.


Cheers,
Jonathan

**Comment by jonathanbaker7** [comment] 2019-02-20 15:48
Certificate updated, problem has been resolved.

**Closed by jonathanbaker7** 2019-02-20 15:48 UTC
