### ISSUE TITLE
QR code cannot help login to SAP Mobile cards

### ISSUE THREAD

**Issue by DivyaKamath7** [SAPDocuments/Tutorials#4676] opened 2020-02-20 15:54 UTC
Hi There Experts, I have the same issue as in old issue "QR Code for SAP Mobile Cards (iOS) ". Strange enough I was able to login once the second time the Mobile cards app says the credentials are incorrect and throws an error" Cannot connect. Please cehck server URL or email and OAuth client iD.

**Comment by jitendrakansal** [comment] 2020-02-21 08:17
@DivyaKamath7 this could be causing because of mobile app is stopped. could you check below? 
once app status is in "started" mode, kill the mobile cards from the background and re-try scanning the QR code. 

In CF trial accounts, all applications are stopped every night for saving resources. This is by design.
If you see some trouble during on-boarding process, make sure that Mobile Services app state is in Started mode. In SAP Cloud Platform cockpit, navigate to subaccount > Spaces> Applications
![image](https://user-images.githubusercontent.com/31536700/75016286-ee646b80-548a-11ea-90c9-fb81b5ad6143.png)

**Comment by MichaelCzcz** [comment] 2020-03-02 07:55
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-03-02 07:55 UTC
