### ISSUE TITLE
Create a Global ABAP Class - empty table snwd_so_inv_item

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#3142] opened 2019-02-26 07:58 UTC
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-new-class.html

Please specify the step you are referring to: all steps

The table used for the tutorial - snwd_so_inv_item - doesn't seem to be filled via transaction SEPM_DG documented here: [The NetWeaver Enterprise Procurement Model - An introduction](https://www.sap.com/documents/2012/09/2a404253-5b7c-0010-82c7-eda71af511fa.html). Is there a simple means to actually fill the table with data? And if not, could the tutorial(s) be rewritten to work with a table which actually contains generated data after running SEPM_DG? SNWD_SO_I would for example have data.

**Comment by julieplummer20** [comment] 2019-02-27 09:16
Hi Baerbel, I've just checked in my system. It's working for me - both snwd_so_inv_item in Data Preview, and my report.
Therefore, whatever the problem is, it does not appear to be specific to SNWD_SO_INV_ITEM. 
Best wishes,
Julie.

**Comment by BaerbelW** [comment] 2019-02-27 10:14
Hi Julie,
the code in the tutorials works, it's just that table snwd_so_inv_item is empty even after transaction SEPM_DG was exectuted to populate the tables in the data model. So, it's difficult to "play" with some actual data as the select doesn't find anything. This is why I'm wondering if there's another means to get data into the table (or - if others have the same issue - to use another but always filled table like SNWD_SO_I for it)?

I just ran the transaction in another DEV-system where all tables were empty to begin with and it didn't add anything to the invoice-table(s) while entries were added to e.g. SNWD_SO_I - Sales Orders:
Products                               106
Employees                               39
Business Partners                       46
Sales Orders                            20
Goods Issue Records                      0
**Sales Order Invoices                     0**
Purchase Orders                         20
Goods Receipt Records                    0
Purchase Order Invoices                  0

I don't see an obvious option on the selection-screen of SEPM_DG to force it to create invoice-entries:
![grafik](https://user-images.githubusercontent.com/18588108/53482991-c6614880-3a80-11e9-9163-174997bf5d56.png)

Do we perhaps have an older version of this program?

Cheers
Bärbel

**Comment by julieplummer20** [comment] 2019-02-27 15:37
Hi Baerbel,
Hmmm. I am not in the office this afternoon, but one possibility: the transaction SEPM_DG_OIA generates these tables, not SEPM_DG. I’ll check this tomorrow and, if so, update the prerequisites accordingly. 
Can you run this too?
Best wishes Julie.

**Comment by julieplummer20** [comment] 2019-02-28 12:19
Hi Baerbel, I have asked for a list of all objects filled by each tx. In the meantime, you can try SEPM_DG_OIA, SEPM_DG_OIA_NEW or tasklist STC01 -> SAP_BASIS_EPM_OIA_CONFIG . 
Otherwise, I 'll look into this when I get back.
Best wishe sJulie.

**Comment by BaerbelW** [comment] 2019-02-28 14:00
Hi Julie,
thanks for the alternative transactions. I ran the underlying program for SEPM_DG_OIA_NEW (couldn't execute the TCode) and now the invoice table does have entries. Some documentation for the programs would help to really know which tables get flled with data - but that's a different topic I guess!

**Comment by julieplummer20** [comment] 2019-03-03 20:22
Hi Baerbel, Thanks for testing this. Am now on holiday w/ limited wifi. Will look into this when I’m back.

**Comment by julieplummer20** [comment] 2019-03-18 08:15
Hi Baerbel, I have asked colleagues for a list of which objects are filled by which transaction / report.
This may become available in time. In the meantime, I have edited the prerequisites to include the correct tx.
Do you mind if I close this issue, since I don't think I can do any more from my side at present?
Thanks for all your feedback - it is really helping us.
Julie.

**Comment by Sdfraga** [comment] 2019-04-08 08:29
Hello,

Same issue here. 
SEPM_DG does not populate snwd_so_inv_item table. 
Ran SEPM_DG_OIA_NEW and the table was populated.
Sérgio Fraga

**Comment by julieplummer20** [comment] 2019-04-08 09:13
Hi Sdfraga,
OK, good to know, thanks. I have updated the prerequisites locally , but still have to push my changes.
Should be visible by EOB tomorrow. 
Best wishes
Julie.

**Comment by thecodester** [comment] 2019-04-18 06:47
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2019-04-18 06:47 UTC
