### ISSUE TITLE
Enable the Push Notification service for your iOS app

### ISSUE THREAD

**Issue by agiguere** [SAPDocuments/Tutorials#3830] opened 2019-08-26 17:27 UTC
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-push-notifications.html

Please specify the step you are referring to

Authentication Problem for Push User:

I have SAP Cloud Platform trust configure to Identity Authentication which proxy the authentication in a corporate identity provider (Microsoft Azure)

Everything works great, I could see my APNS device token has been uploaded in my user registration, I assign the Notification User role to my user but when I tried to send a notification
I get an error saying Send Notification failed!

If I tried to send the notification with the PUSH API in Postman, I got an http 401

is there a specific configuration for SAML ?

thanks

**Comment by KevinMuessig** [comment] 2019-12-03 00:52
Hi @agiguere ,

I can't reproduce your setup but I can check in with the experts.

Please give me some time.

Thanks,

Kevin

**Comment by agiguere** [comment] 2019-12-03 05:09
hi @KevinMuessig , this issue has been fixed, you won't believe what it was!

my APNS configuration in SCPms was using APNS token and not the certificate option, our instance was running in SAP Toronto data center in Canada, after I contacted SAP about this issue they told me the token functionality was not active on their side, so they activate it and it is now working ... From an end-user perspective it was impossible to troubleshoot

Alex

**Comment by MichaelCzcz** [comment] 2019-12-04 09:10
@agiguere Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2019-12-04 09:10 UTC
