### ISSUE TITLE
Create an SAPUI5 Purchase Order App

### ISSUE THREAD

**Issue by I079506** [SAPDocuments/Tutorials#3468] opened 2019-05-07 14:33 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-ms-graph-create-app.html

Please specify the step you are referring to 3

provides misleading information to update the neo.json with below
"path": "/sap/opu/odata",
"target": {
  "type": "destination",
  "name": "SAP_Gateway",
  "entryPath": "/sap/opu/odata"
},

once I did it, my app was not reaching the odata service.

**Comment by IObert** [comment] 2019-05-08 07:58
Good catch! This comment is clearly outdated and should be removed.

**Comment by IObert** [comment] 2019-05-08 11:08
I'll keep this issue open until the fix is in the production system

**Comment by I079506** [comment] 2019-05-09 11:16
Sorry for hijacking this thread.
I would like to ask question, I see that this session is referenced from Office 365 session
https://developers.sap.com/mission.teched-2018-microsoft.html

Where there is Checkpoint and Price, can you share with me reference explaining how to take benefit/use this Checkpoint and Price?

Many thanks!,
Ondrej

**Comment by IObert** [comment] 2019-05-09 11:21
Hi @I079506,

this mission was designed for TechEd 2018 where we gave out prices for completed missions. Unfortunately, we don't give out prices after the event.
Please ignore those steps.

**Comment by I079506** [comment] 2019-05-09 11:25
Was thinking about using this to build virtual honor room (without real extra bonus to the attendee) so people are more motivated to execute the scenarios.
This could be nicely tracked on company level and create more competitive ecosystem.

0.

**Comment by thecodester** [comment] 2019-05-12 06:07
The issue seems to be resolved (the tutorial was updated), so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2019-05-12 06:07 UTC

**Comment by IObert** [comment] 2019-05-13 07:49
I'd like to add two more comments to this thread.

1.) We will remove the checkpoints/prices from this mission.
2.) I like the idea of a virtual "honor room". In fact, we do something similar in place with our [Badges](https://www.sap.com/community/resources/missions-badges.html#Developer_Tutorial_Missions)
