### ISSUE TITLE
Set up SAP Data Hub, developer edition 2.4

### ISSUE THREAD

**Issue by dash042** [SAPDocuments/Tutorials#3148] opened 2019-02-27 15:44 UTC
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-setup.html

- Creation of Docker Image: image-name (FROM) is not correct
- Docker RUN command is incorrect

More specific: 
Command
`docker run -ti --env VORA_USERNAME=admin --env VORA_PASSWORD=admin --publish 127.0.0.1:8090:8090 --publish 127.0.0.1:9225:9225 --publish 30115:30115 --name datahub --hostname datahub --network dev-net sapdatahub/dev-edition-base:15.0-01 run --agree-to-sap-license`
results in
`/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"run\": executable file not found in $PATH".`

**Comment by anishgupta85** [comment] 2019-02-28 12:59
Hi,
Did you build the image in the directory where you downloaded the developer edition?
Regards,
Anish

**Comment by dash042** [comment] 2019-02-28 18:05
Hi Anish,

yes.



___
Sent from my mobile

**Comment by anishgupta85** [comment] 2019-03-04 10:05
Hi ,
Actually you are trying to run the base image and this will not work.
Could you first try to run the below command?
docker run -ti --env VORA_USERNAME=admin --env VORA_PASSWORD=admin --publish 127.0.0.1:8090:8090 --publish 127.0.0.1:9225:9225 --publish 30115:30115 --name datahub --hostname datahub --network dev-net datahub run --agree-to-sap-license
Regards,
Anish

**Comment by dash042** [comment] 2019-03-04 12:07
Hi,
I did the following:
1. I downloaded DEV-Edition & unzipped it
2. In the unzip directory I reveled over my new files: `dev-edition-base.Dockerfile  Dockerfile  **files**  **kubernetes**  **readme**`
3. I executed the command: `docker build --tag datahub .`
4. I got annoyed over the following error:
```
Sending build context to Docker daemon 1.028 GB
Step 1/12 : ARG BASEIMAGE="sapdatahub/dev-edition-base:15.0-01"
Please provide a source image with `from` prior to commit
```
5. I read the README.md and realized I had to create 2 images... both of which didn't work "out of the box" since Docker wants a "FROM" at the beginning of Dockerfiles - so I changed the 2 dockerfiles accordingly
6. I was shortly happy about a starting datahup - until I saw several errors:
a) `tar (child): /tmp/Downloads/datahub-app-base-vsolution-*.tar.gz: Cannot open: No such file or directory`
b) `2019-03-04T12:01:28+00:00 Connection manager not present. Cannot start`
and finally:
c) `2019-03-04T12:04:05+00:00 -------- executing VORA_set_credentials --------
2019-03-04T12:04:05+00:00 creating user: vora in userstore
removing user vora in /etc/vora-security/default/htpasswd
User vora created in /etc/vora-security/default/htpasswd.
2019-03-04T12:04:05+00:00 creating user: vora in vora
connecting to 172.18.0.2 at port 2202 (172.18.0.2:2202) ...
switched to existing session ""
Failed sending request, error code=105 : please see trace for details
cease to connect to 172.18.0.2:2202...
connecting to 172.18.0.2 at port 2202 (172.18.0.2:2202) ...
Failed sending request, error code=101 : please see trace for details
error: no active session. disconnecting
cease to connect to 172.18.0.2:2202...
disconnected from 172.18.0.2 at port 2202
error: no connection
error: no connection
cease to connect to 0.0.0.0:0...
connecting to 172.18.0.2 at port 2202 (172.18.0.2:2202) ...
Failed sending request, error code=101 : please see trace for details
error: no active session. disconnecting
cease to connect to 172.18.0.2:2202...
disconnected from 172.18.0.2 at port 2202
error: no connection
error: no connection
error: no connection
cease to connect to 0.0.0.0:0...
`

Sincerely,
Daniel

**Comment by anishgupta85** [comment] 2019-03-04 12:22
Hi Daniel,
Let's try the following:-
1. Issue the command for creation of the base image docker build --tag sapdatahub/dev-edition-base:15.0-01 -f dev-edition-base.Dockerfile .

2. Issue the command for creation of the final image docker build --tag sapdatahub/dev-edition:2.4 .

3. docker run -ti --env VORA_USERNAME=admin --env VORA_PASSWORD=admin --publish 127.0.0.1:8090:8090 --publish 127.0.0.1:9225:9225 --publish 30115:30115 --name datahub --hostname datahub --network dev-net sapdatahub/dev-edition:2.4 run --agree-to-sap-license

let me know if it works.
Regards,
Anish

**Comment by dash042** [comment] 2019-03-04 15:01
Hi Anish,

I have tried these exact commands.
I also tried something different - the ARG problem should have clued me in... I updated to the latest docker CE version and built the image again.

However...  the errors I posted earlier remain and the start fails trying to connect to 172.18.0.2:2202 - i.e. the container's IP.
![image](https://user-images.githubusercontent.com/11177097/53741446-b4274600-3e96-11e9-8398-37394fea19e1.png)


Sincerely,
Daniel

**Comment by anishgupta85** [comment] 2019-03-04 15:09
Hi Daniel,
Did you create the network as shown below:-

docker network create dev-net

Regards,
Anish

**Comment by dash042** [comment] 2019-03-04 15:23
Yes - if not the run command would have failed:

NETWORK ID          NAME                DRIVER              SCOPE
8200a147b2db        dev-net             bridge              local

**Comment by dash042** [comment] 2019-03-05 16:18
got it **working**:
1. re-created image(s) & network after docker CE update
2. changed port publishing to 0.0.0.0 (see below)

`docker run -ti --env VORA_USERNAME=vora --env VORA_PASSWORD=password123 -p 8090:8090 -p 9225:9225 -p 30115:30115 --name datahub --hostname datahub --network dev-net sapdatahub/dev-edition:2.4 run --agree-to-sap-license`

I still get errors documented above - but now I get to "executing status_loop" and I can access the Data Hub Modeler...

THANK YOU for you patience and help, Anish!

**Comment by thecodester** [comment] 2019-03-05 16:52
If you are satisfied and the issue is resolved, please close the issue. Thanks.

**Closed** 2019-03-07 15:30 UTC
