### ISSUE TITLE
Creating an app using the SAP Cloud Platform SDK for iOS Assistant

### ISSUE THREAD

**Issue by danricko** [SAPDocuments/Tutorials#1480] opened 2017-03-31 04:14 UTC
I followed up to step 9, however the iOS SDK Assistant crashes after I press the finish button, while it is trying to create the project. 

Most of the XCode project seems to be there, however the proxy classes are missing. I'm guessing it crashes while creating these. 

Is there a way to generate the proxy classes manually?

**Comment by pdominique** [comment] 2017-03-31 09:56
Apparently proxy classes can be generated from the command line: https://blogs.sap.com/2017/03/31/sap-cloud-platform-sdk-for-ios-did-you-know-that.../

**Comment by dv1adm** [comment] 2017-04-06 09:42
Getting the same issue. Did manual proxy class generation work out?

**Comment by qualiture** [comment] 2017-11-15 09:01
Hi @danricko,

See the comment by @pdominique.

FYI, with SDK v2.0, you can install the command line tools from the SDK Assistant. From its top menu, go to **SAP Cloud Platform SDK for iOS Assistant > Install Tools** to install them on your local system.

If the issue is resolved, you may close this issue

**Comment by pdominique** [comment] 2017-11-15 10:36
Hi,

If the assistant fails, use the command line tool to generate the proxy classes. The error in the console might not be very helpful with the assistant. However you can get more details when using the proxy generator via command line.

Example: in my case the classes could not be generated because I had a function import called GetEntityNames. The generator wa trying to generate the same function twice, one to call the function import and the other one to call the get entity set for entity EntityName. After deleting the function import, the classes could be generated.

Cheers,
Pierre

**Comment by thecodester** [comment] 2017-12-26 10:33
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2017-12-26 10:33 UTC
