### ISSUE TITLE
Portal Service icon updated- Build Your First Portal Site

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5320] opened 2020-06-16 04:43 UTC
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html
Navigate to portal service section

Remark- Screenshot has to be updated

Expected
![image](https://user-images.githubusercontent.com/7221229/84732706-0328ba00-afba-11ea-8a66-0e3a40f5cba1.png)

Actual
![image](https://user-images.githubusercontent.com/7221229/84732712-06bc4100-afba-11ea-832e-0ffde88db1a7.png)

**Comment by IrisSasson** [comment] 2020-07-12 09:06
Hi
The correct icon is shown in the tutorial. Maybe there was some issue in the production when you logged this defect. Anyway- please see this doesn't reproduce

Thanks
Iris.

**Comment by MichaelCzcz** [comment] 2020-07-13 12:12
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-07-13 12:12 UTC
