### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by Redah7** [SAPDocuments/Tutorials#4626] opened 2020-02-12 08:53 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Step 4: Provision SAP Cloud Platform Integration tenant
![image](https://user-images.githubusercontent.com/44206383/74318397-d3587400-4d85-11ea-9e77-e82623ca0705.png)

When I attempt to go to the application, I get a "Bad Request" error? 
![image](https://user-images.githubusercontent.com/44206383/74318421-e4a18080-4d85-11ea-98ea-5a56c6ece446.png)

**Comment by gauthamkrishna-sap** [comment] 2020-02-12 13:40
Hello,
Thanks for the feedback. Have you assigned the required roles for this?
Thanks & Best Regards, Gautham

**Comment by Redah7** [comment] 2020-02-12 14:56
Hello,

Yes I have. I added the required roles to the role collection
"Tenant_Administartor", see below.

Other things I have tried:
1. Unsubscribed and re-subscribed to the "process integration" application
in my subaccount.
2. Setup a new subaccount, subscribed to the application, created and
assigned roles.

Both of these options did not work. When I click on "go to application" it
open a URL but when I try to log in with my credentials it just says "Bad
request"

I'm not sure what else I could try or what I could be doing incorrectly.
Please help.
[image: image.png]

Kind regards,
Redah

**Comment by gauthamkrishna-sap** [comment] 2020-02-12 15:03
Hello,

This is indeed strange: can you please check if your default browser certificate is being used (this should ideally throw HTTP401 exception, but sometimes 400 as well).

Thanks & Best Regards,
Gautham

**Comment by Redah7** [comment] 2020-02-12 15:13
Hi,

Just some more information.

Yesterday I was able to provision a SAP Cloud Platform Integration tenant.
It gave me the tenant url (
https://s0021484020trial.it-cpitrial01.cfapps.eu10.hana.ondemand.com/itspaces
).

I created the service instance and service keys and saved it. I am just
struggling to get back into the Process Integration application to create a
integration package and integration flow.

Kind regards,
Redah

**Comment by gauthamkrishna-sap** [comment] 2020-02-12 15:34
Hi Redah,

When I access your tenant URL, I can access the login page to the provisioning app. So, I am unable to reproduce your issue. Can you please try in a different browser, or please clear your cache, cookies and try?

Thanks & Best Regards,
Gautham

**Comment by Redah7** [comment] 2020-02-12 17:06
Hi Gautham,

I changed my browser and it worked. Thank you!!

Kind regards,
Redah

**Comment by gauthamkrishna-sap** [comment] 2020-02-12 17:57
Thanks for the update :) happy developing!

Thanks & Best Regards,
Gautham
Sent from my iPhone, Kindly excuse any brevity

On 12. Feb 2020, at 18:07, Redah7 <notifications@github.com> wrote:

﻿Hi Gautham,

I changed my browser and it worked. Thank you!!

Kind regards,
Redah

**Comment by MichaelCzcz** [comment] 2020-02-17 09:08
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-02-17 09:08 UTC
