### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#3620] opened 2019-06-12 07:16 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-03-add-database.html

Step 1: Add a database

As reported from Mary Jose in [SAP CAP: Build of /bookshop/db failed](https://answers.sap.com/questions/12706870/sap-cap-build-of-bookshopdb-failed.html) the build fails with this error message:

```
09:09:46 (Executor) Build command failed : Build failed: Failed during post build event: Failed to create JSON from build log: json: cannot unmarshal string into Go struct field BuilderLog.level of type int
09:09:46 (Executor) The "task for hdb build" process finished with code 1
09:09:46 (Executor) Build of /bookshop-java/db failed.
```

I was able to replicate this issue in two different SCP CF Trial Accounts using the SAP Web IDE Full Stack and my project: [bookshop-java](https://github.com/gregorwolf/bookshop-java)

**Comment by renejeglinsky** [comment] 2019-06-13 12:34
@gregorwolf The issue is fixed. Please try again.
I had to go into my space and delete the app _hdispacedeploy<GUID_NUMBER>_ and then it worked.

**Comment by thecodester** [comment] 2019-06-19 09:54
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2019-06-19 09:54 UTC
