### ISSUE TITLE
Developing and deploying a basic Java application on SAP Cloud Platform

### ISSUE THREAD

**Issue by jonathan-benn** [SAPDocuments/Tutorials#1376] opened 2017-02-28 20:23 UTC
Hi,

I followed your instructions, but when I deployed my Hello World app to HCP I got a weird error message:

Java version [8] is not compatible with the currently specified runtime; use runtime neo-java-web 2.x or 3.x

The solution was to go into Eclipse's Window > Preferences, then option Server > SAP HANA Cloud and set the SDK location to a version 2 or 3 (the Tomcat ones, not the recommended v1 Java Web one!). I deleted my server and then re-created a new one and it was then able to deploy.

Since Java 8 is the standard now, it might be a good idea to update your article to suggest using Tomcat 8 instead, so that the runtime is Java 8 compatible.

I hope that helps,

--Jonathan

**Comment by Zhuinden** [comment] 2017-10-17 14:18
@akula86 have you guys considered updating the tutorial to use Neo SDK 3.x  instead of Neo SDK 1.x so that your tutorial is Java 8 compatible, instead of being ***ONLY JAVA 6 COMPATIBLE*** which does NOT work even if you specify Java 6 explicitly?

Thank you

**Comment by akula86** [comment] 2017-10-17 15:34
@Zhuinden - @jonathan-benn Sorry about that - this issue was closed inadvertently. All issues should have a proper disposition before closing.

**Comment by Zhuinden** [comment] 2017-10-17 16:09
Thanks for looking into it! It kinda took us 3 hours to get a hello world out to the cloud platform because we couldn't get Neo 1.x to work.

**Comment by Zhuinden** [comment] 2017-10-18 13:19
In fact, Neo 1.x / Java Web Profile is deprecated and scheduled for removal in 2017 december

**Comment by jonathanbaker7** [comment] 2018-03-16 15:08
Just to keep everyone updated.

I've checked with the cloud team who originally authored this tutorial, and they are looking at updating the entire "getting started" in Neo series.  Unfortunately, it keeps getting put off.  So I'm going to block some time in the next few weeks to take a look, and try to update this to TomEE7 (the latest container, with full EE support).  This will also switch to Java 8 (we don't have a Java 9 implementation yet).

In the meantime, the same code works in TomEE 7, by downloading a different Zip file from the web site (just use the TomEE7 link), and then using that server.

I'll keep you posted...

**Comment by thecodester** [comment] 2018-06-06 09:18
Issue closed since a year has elapsed since it was opened. If the issue is still relevant, please reopen the issue or open a new one.

**Closed by thecodester** 2018-06-06 09:18 UTC
