### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by pavan141080** [SAPDocuments/Tutorials#4177] opened 2019-11-08 21:01 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to
2. In your subaccount, select Subscriptions > Process Integration.
I am not finiding SaaS application Process Integration in my trial Subaccount

![SCP_pi](https://user-images.githubusercontent.com/56557186/68510235-8b7ef980-0238-11ea-8582-ea0335996e99.png)

**Comment by gauthamkrishna-sap** [comment] 2019-11-10 13:23
Hi Pavan,
Did you create a new subaccount for this trial? 
You need to entitle your subaccount with the Process Integration service under the **Entitlements** section. 
Best Regards, Gautham

**Comment by pavan141080** [comment] 2019-11-13 21:47
Process Integration is NOT part of Entitlements, still I don't see Process Integration Under Subscriptions. I tried new trial account. Please find the attached screen prints

<img width="926" alt="CPI1" src="https://user-images.githubusercontent.com/56557186/68806480-987e5d00-062b-11ea-95ae-25a4d20eb88f.png">
<img width="916" alt="CPI2" src="https://user-images.githubusercontent.com/56557186/68807088-cb752080-062c-11ea-9aaf-4699ec79bc25.png">

**Comment by gauthamkrishna-sap** [comment] 2019-11-13 22:06
Hello Pavan,
Sorry for the trouble.
Can you please provide your subdomain ID & global account ID so that I can ask my team to check this?
Best Regards, Gautham

**Comment by Kyle-MacKenzie** [comment] 2020-01-02 13:00
Hello,
Was this issue ever resolved? I am currently working through a process integration tutorial and am experiencing the same issue. I am using a trial account, and when I navigate to subscriptions to subscribe to Process Integration I do not see it in the subscription list.
Thank you,
Kyle

**Comment by gauthamkrishna-sap** [comment] 2020-01-03 09:19
Hi Kyle,
I, unfortunately, did not hear back from Pavan. However, this is not a common issue. 
For your case, I request you to please check the entitlements for your subaccount. If your subaccount is entitled with Process Integration Runtime & you still can't see the tile, please share your Global Account & Subaccount ID. I will request our team to check your case specifically. 
Thanks & Best Regards.
Gautham

**Comment by Kyle-MacKenzie** [comment] 2020-01-03 14:16
Hi Gautham,
I have checked my entitlements and I do have access to the Process Integration Runtime as expected. To note, the quota and usage are both limited, as I am using a trial account. I have also attempted creating a new account, and setting the entitlement, with no luck.
For my trial account, my global account ID is **05985c19-7c5d-4320-a706-d6989203d26e**, and my subaccount ID is **ba085114-a8a7-428e-952a-a6b7544f1099**.
Thank you,
Kyle

**Comment by gauthamkrishna-sap** [comment] 2020-01-04 17:23
Hello Kyle,
Thank you for checking this. Another small check you can do is if your trial account is in the EU zone. In the meantime, I will create an incident and follow up as well.
Thanks & Best Regards,
Gautham

**Comment by Kyle-MacKenzie** [comment] 2020-01-06 11:35
Hi Gautham,
I checked my account and confirmed that my Global account is in EU, while my trial subaccount is in US. I have created another subaccount with the location set to EU, and I can now see the Process Integration in that EU subaccount. My issue appears to be resolved
Thank you,
Kyle

**Comment by gauthamkrishna-sap** [comment] 2020-01-07 08:13
Hello Kyle,
Thank you for the confirmation. 
Best Regards, Gautham

**Comment by thecodester** [comment] 2020-01-08 06:50
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2020-01-08 06:50 UTC
