### ISSUE TITLE
Add a Web Dynpro ABAP App to Your Launchpad Page

### ISSUE THREAD

**Issue by Waltersen1971** [SAPDocuments/Tutorials#4893] opened 2020-04-07 13:20 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-freestyle-site-wd-add.html

Hello,
I have build thr webdynpro app. If I try to start it via portal I get this:

500 SAP Internal Server Error
ERROR: URL-Parameter sap-theme ist nicht in der HTTP White-List vorhanden (termination: RABAX_STATE)

I have opened a ticked, # 4454, had some emails (with Iris Sasson, who told me to use feedback in the tutorial). She linked the cloud foundry tutorial but this is referring to the neo tutorial. 

Error is still there, I can reproduce it. Seems to be a problem of the backend, not of the portal.

Regards

**Comment by Waltersen1971** [comment] 2020-05-07 15:35
It is not browser dependent it comes with Firfox and Chrome. Found this: 2578665 - How to maintain the table HTTP_WHITELIST

Could you maybe confirm if this is a problem of the backend server? So I would let it be and terminate the tutorial.

**Comment by IrisSasson** [comment] 2020-05-13 09:10
Hi 
This is Iris. I wanted to have you use the tutorial in order to avoid any "how-to" issues so that you know how things should be configures. If this reproduce we need to continue with the ticket. Can you please send me you ticket number and i will try to promote it? You have my email and if not let me know

Thanks
IRis.

**Comment by Waltersen1971** [comment] 2020-05-13 10:50
Hello,

I thought # 4893 is already my ticket number.

What I have done is:

1.) Use link for neo portal

https://flpportal-p097818trial.dispatcher.hanatrial.ondemand.com/sites?siteId=d900fed3-f7cb-4f80-b5b8-503ed5a7d8c3&evictCache=true#Home-show

2.) These are the apps from the tutorial



While product list works, search POs makes this:




I got this on my work PC (before Corona). I get it now, when I use my work
surrounding via citrix receiver. Browser is Edge.

If I use my private PC I get this via Firefox and Chrome.

In my opinion it is not a problem of the browser, but a problem of the
server, where the webdynpro app is executed:


Under App Resources Details enter the following values:
App Type = Web Dynpro ABAP
Application ID = S_EPM_FPM_PO (the transaction ID associated with the
application we wish to add)
System Alias = ES5 (the name of the destination connecting to the SAP
Backend)
SAP Business Client URI = /ui2/nwbc/~canvas;window=app/WDA/S_EPM_FPM_PO
(path to the SAP NetWeaver Business Client used to run the app together
with transaction ID).

This is from the tutorial.

How I said, I also found a Note for this topic.

Regards

_____________________________________________________
Jan Schlichting
Deutsche Bundesbank
Zentrale
IT-Plattformanagement Drittprodukte

Willy-Brandt-Straße 73
20459 Hamburg

Tel.: 040 3707-6571
E-Mail: jan.schlichting@bundesbank.de
www.bundesbank.de

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail oder von Teilen dieser Mail ist nicht gestattet.

Wir haben alle verkehrsüblichen Maßnahmen unternommen, um das Risiko der
Verbreitung virenbefallener Software oder E-Mails zu minimieren, dennoch
raten wir Ihnen, Ihre eigenen Virenkontrollen auf alle Anhänge an dieser
Nachricht durchzuführen. Wir schließen außer für den Fall von Vorsatz oder
grober Fahrlässigkeit die Haftung für jeglichen Verlust oder Schäden durch
virenbefallene Software oder E-Mails aus.

Jede von der Bank versendete E-Mail ist sorgfältig erstellt worden, dennoch
schließen wir die rechtliche Verbindlichkeit aus; sie kann nicht zu einer
irgendwie gearteten Verpflichtung zu Lasten der Bank ausgelegt werden.
______________________________________________________________________

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorised copying, disclosure or distribution of  the material in this
e-mail or of parts hereof is strictly forbidden.

We have taken precautions to minimize the risk of transmitting software
viruses but nevertheless advise you to carry out your own virus checks on
any attachment of this message. We accept no liability for loss or damage
caused by software viruses except in case of gross negligence or willful
behaviour.

Any e-mail messages from the Bank are sent in good faith, but shall not be
binding or construed as constituting any kind of obligation on the part of
the Bank.

**Comment by thecodester** [comment] 2020-06-07 06:43
@IrisSasson @Waltersen1971 Have you guys resolved this offline?

**Comment by IrisSasson** [comment] 2020-06-07 07:06
Hi 

Sorry for the delay, 
Did you try doing this on Cloud Foundry? (note that there is a step by step tutorial for CF as well). After you try on CF let me know how it worked. 
In general, I think you should focus on CF environment on trial. We had 10 people follow this in the last week and it works for them, so i expect it would work for you too.

I don't always get notifications from here and you can email me directly to expedite resolution.
Thanks
Iris.

**Comment by IrisSasson** [comment] 2020-06-07 07:07
Also, because it works on CF the problem is not in the backend

**Comment by Waltersen1971** [comment] 2020-06-08 07:00
Hello,

there is another tutorial for cloud foundry and that worked well.

It is this one: https://developers.sap.com/mission.portal-cf.html. There
was a similar task and that worked well.

Regards
_____________________________________________________
Jan Schlichting
Deutsche Bundesbank
Zentrale
IT-Plattformanagement Drittprodukte

Willy-Brandt-Straße 73
20459 Hamburg

Tel.: 040 3707-6571
E-Mail: jan.schlichting@bundesbank.de
www.bundesbank.de

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail oder von Teilen dieser Mail ist nicht gestattet.

Wir haben alle verkehrsüblichen Maßnahmen unternommen, um das Risiko der
Verbreitung virenbefallener Software oder E-Mails zu minimieren, dennoch
raten wir Ihnen, Ihre eigenen Virenkontrollen auf alle Anhänge an dieser
Nachricht durchzuführen. Wir schließen außer für den Fall von Vorsatz oder
grober Fahrlässigkeit die Haftung für jeglichen Verlust oder Schäden durch
virenbefallene Software oder E-Mails aus.

Jede von der Bank versendete E-Mail ist sorgfältig erstellt worden, dennoch
schließen wir die rechtliche Verbindlichkeit aus; sie kann nicht zu einer
irgendwie gearteten Verpflichtung zu Lasten der Bank ausgelegt werden.
______________________________________________________________________

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorised copying, disclosure or distribution of  the material in this
e-mail or of parts hereof is strictly forbidden.

We have taken precautions to minimize the risk of transmitting software
viruses but nevertheless advise you to carry out your own virus checks on
any attachment of this message. We accept no liability for loss or damage
caused by software viruses except in case of gross negligence or willful
behaviour.

Any e-mail messages from the Bank are sent in good faith, but shall not be
binding or construed as constituting any kind of obligation on the part of
the Bank.

**Comment by Waltersen1971** [comment] 2020-06-08 07:11
Hello,

as it worked on foundry a similar case (see my other mail), shall it it be
settled? Because foundry is the only supported tech in the future?

Regards
_____________________________________________________
Jan Schlichting
Deutsche Bundesbank
Zentrale
IT-Plattformanagement Drittprodukte

Willy-Brandt-Straße 73
20459 Hamburg

Tel.: 040 3707-6571
E-Mail: jan.schlichting@bundesbank.de
www.bundesbank.de

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail oder von Teilen dieser Mail ist nicht gestattet.

Wir haben alle verkehrsüblichen Maßnahmen unternommen, um das Risiko der
Verbreitung virenbefallener Software oder E-Mails zu minimieren, dennoch
raten wir Ihnen, Ihre eigenen Virenkontrollen auf alle Anhänge an dieser
Nachricht durchzuführen. Wir schließen außer für den Fall von Vorsatz oder
grober Fahrlässigkeit die Haftung für jeglichen Verlust oder Schäden durch
virenbefallene Software oder E-Mails aus.

Jede von der Bank versendete E-Mail ist sorgfältig erstellt worden, dennoch
schließen wir die rechtliche Verbindlichkeit aus; sie kann nicht zu einer
irgendwie gearteten Verpflichtung zu Lasten der Bank ausgelegt werden.
______________________________________________________________________

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorised copying, disclosure or distribution of  the material in this
e-mail or of parts hereof is strictly forbidden.

We have taken precautions to minimize the risk of transmitting software
viruses but nevertheless advise you to carry out your own virus checks on
any attachment of this message. We accept no liability for loss or damage
caused by software viruses except in case of gross negligence or willful
behaviour.

Any e-mail messages from the Bank are sent in good faith, but shall not be
binding or construed as constituting any kind of obligation on the part of
the Bank.

**Comment by IrisSasson** [comment] 2020-06-08 08:58
It should work on Neo as well. CF is supported in addition to Neo

**Comment by Waltersen1971** [comment] 2020-06-11 10:17
Hello Iris,

but for me I does not work with Neo. I tried it several times with
different browsers. Always I got this error.

I do not know what shall I do.

Regards
_____________________________________________________
Jan Schlichting
Deutsche Bundesbank
Zentrale
IT-Plattformanagement Drittprodukte

Willy-Brandt-Straße 73
20459 Hamburg

Tel.: 040 3707-6571
E-Mail: jan.schlichting@bundesbank.de
www.bundesbank.de

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail oder von Teilen dieser Mail ist nicht gestattet.

Wir haben alle verkehrsüblichen Maßnahmen unternommen, um das Risiko der
Verbreitung virenbefallener Software oder E-Mails zu minimieren, dennoch
raten wir Ihnen, Ihre eigenen Virenkontrollen auf alle Anhänge an dieser
Nachricht durchzuführen. Wir schließen außer für den Fall von Vorsatz oder
grober Fahrlässigkeit die Haftung für jeglichen Verlust oder Schäden durch
virenbefallene Software oder E-Mails aus.

Jede von der Bank versendete E-Mail ist sorgfältig erstellt worden, dennoch
schließen wir die rechtliche Verbindlichkeit aus; sie kann nicht zu einer
irgendwie gearteten Verpflichtung zu Lasten der Bank ausgelegt werden.
______________________________________________________________________

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorised copying, disclosure or distribution of  the material in this
e-mail or of parts hereof is strictly forbidden.

We have taken precautions to minimize the risk of transmitting software
viruses but nevertheless advise you to carry out your own virus checks on
any attachment of this message. We accept no liability for loss or damage
caused by software viruses except in case of gross negligence or willful
behaviour.

Any e-mail messages from the Bank are sent in good faith, but shall not be
binding or construed as constituting any kind of obligation on the part of
the Bank.

**Comment by IrisSasson** [comment] 2020-07-07 12:23
Hi
Please email me at iris.sasson@sap.com and we can have a short meeting to see what is wrong. In general, we recommend using Cloud Foundry

Thanks
Iris.

**Comment by MichaelCzcz** [comment] 2020-07-21 09:34
@IrisSasson Any updates? Can I close the issue?

**Comment by IrisSasson** [comment] 2020-07-21 11:40
Hi, I didn't see any update on this.

**Comment by MichaelCzcz** [comment] 2020-08-03 07:36
@IrisSasson What is the status of this issue?

**Comment by IrisSasson** [comment] 2020-08-03 07:59
I didn't get any update, i guess you can close it

**Comment by MichaelCzcz** [comment] 2020-08-04 07:36
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-08-04 07:36 UTC

**Comment by Waltersen1971** [comment] 2020-08-10 11:01
Hello,

I have been 4 weeks in vacation. I am still getting this error, like all
the months before.

I have already written what I have done. When there is no solution, so let
the ticked be closed.

Regards
_____________________________________________________
Jan Schlichting
Deutsche Bundesbank
Zentrale
IT-Plattformanagement Drittprodukte

Willy-Brandt-Straße 73
20459 Hamburg

Tel.: 040 3707-6571
E-Mail: jan.schlichting@bundesbank.de
www.bundesbank.de

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail oder von Teilen dieser Mail ist nicht gestattet.

Wir haben alle verkehrsüblichen Maßnahmen unternommen, um das Risiko der
Verbreitung virenbefallener Software oder E-Mails zu minimieren, dennoch
raten wir Ihnen, Ihre eigenen Virenkontrollen auf alle Anhänge an dieser
Nachricht durchzuführen. Wir schließen außer für den Fall von Vorsatz oder
grober Fahrlässigkeit die Haftung für jeglichen Verlust oder Schäden durch
virenbefallene Software oder E-Mails aus.

Jede von der Bank versendete E-Mail ist sorgfältig erstellt worden, dennoch
schließen wir die rechtliche Verbindlichkeit aus; sie kann nicht zu einer
irgendwie gearteten Verpflichtung zu Lasten der Bank ausgelegt werden.
______________________________________________________________________

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorised copying, disclosure or distribution of  the material in this
e-mail or of parts hereof is strictly forbidden.

We have taken precautions to minimize the risk of transmitting software
viruses but nevertheless advise you to carry out your own virus checks on
any attachment of this message. We accept no liability for loss or damage
caused by software viruses except in case of gross negligence or willful
behaviour.

Any e-mail messages from the Bank are sent in good faith, but shall not be
binding or construed as constituting any kind of obligation on the part of
the Bank.
