### ISSUE TITLE
Implement a CDS Custom Entity and Query Implementation Class

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#5842] opened 2020-09-12 09:23 UTC
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-a4c-create-custom-entity.html

Step 7: Create service binding

Before this step the creation of a Service Definition is missing. Without the Service Definition the Service Binding can't be created. Here is a sample:

```
@EndUserText.label: 'Travel Service Definition'
define service ZSD_TRAVEL_DATA_GW2 {
  expose ZCE_TRAVEL_DATA_GW2 as Travel;
}
```

**Comment by julieplummer20** [comment] 2020-09-15 06:52
Hi Gregor,
This tutorial is part 5 of a 5-part mission. If you try to do it, without completing parts 1-4, you may not get the expected result.
Step 7 actually says "Select your service definition, ZCE_TRAVEL_DATA_XXX, created in the tutorial Create a Service Consumption Model and choose New > Create Service Binding from the context menu."

More broadly: The Mission is listed on the right. I have suggested that it should be top and center just before pre-requisites. I will raise this again.

BR Julie.

**Comment by gregorwolf** [comment] 2020-09-15 12:21
Maybe it's possible to directly link to the step [Step 7: Create CDS custom entity](https://developers.sap.com/tutorials/abap-environment-create-service-consumption-model.html#95236123-f911-4508-81d6-2e59864b13c7)

**Comment by julieplummer20** [comment] 2020-09-17 07:32
Hi Gregor,
I have checked with the team responsible for actually turning my .md and .png files into proper .html, and integrating them in missions etc. They have suggested that I don't do this right now, in case changes are made to the other tutorial that lead to an unexpected behaviour.
However, I have suggested that we look at this for a future sprint.
Thanks a lot,
Julie.

**Comment by MichaelCzcz** [comment] 2020-09-17 13:37
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-09-17 13:37 UTC
