### ISSUE TITLE
Tutorial fiori-ios-hcpms-fioriuikit: Class for object cell invalid

### ISSUE THREAD

**Issue by pfefferf** [SAPDocuments/Tutorials#1573] opened 2017-04-06 14:29 UTC
Hi,

in tutorial https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/fiori-ios-hcpms-fioriuikit/fiori-ios-hcpms-fioriuikit.md (https://www.sap.com/developer/tutorials/fiori-ios-hcpms-fioriuikit.html) it is mentioned that a a class "ObjectCell" should be set for the table view cell added to the view.

From my point of view this is not correct. Class FUIObjectTableViewCell should be used.
Also the module information in the text (SAPFiori) is different to the module information in the screenshot for the cells attribute inspector view (here FioriUIKit is mentioned).

In the coding also to the unknown class ObjectCell is used.
The used property "mainStackWidth" is not available. At least not for the Object Cell View class.

Names refer to old names available in the EA version of the SDK. Tutorial should reflect the names of the GA version. For more information: https://help.sap.com/viewer/fc1a59c210d848babfb3f758a6f55cb1/Latest/en-US/4eef90a7810b4c18bf66566ecf2a76d5.html

Thx & Regards,
Florian

**Comment by amit1agrawal** [comment] 2017-04-07 10:22
Hi Florian,
You are right. The older name of the class was ObjectCell and the new name is FUIObjectTableViewCell. Similarly, FioriUIKit is older name for SAPFiori. Probably screenshots were taken before the names got updated :)

Regards,
Amit

**Comment by akula86** [comment] 2017-04-19 19:57
@qualiture please review

**Comment by qualiture** [comment] 2017-04-19 20:13
Duplicate of #1623, fixed with commit https://github.com/SAPDocuments/Tutorials/commit/bdafc909ab8e08b404c8926a1fc310fd83a5d6be

**Closed** 2017-04-19 20:20 UTC
