### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Tutorials#5290] opened 2020-06-12 13:47 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Landscape : trial Us region

**Step 1 Edit Integration Flow** 

In Step1 4th instruction , In Edit mode  the screenshot doesn't show "Simulation mode" toggle button in design time
![SimulationModeinDT](https://user-images.githubusercontent.com/33411431/84509448-57454d00-ace1-11ea-9173-e898ab383758.PNG)

**Comment by Vikramkulkarni01** [comment] 2020-06-15 07:23
Hi @mounikat987, 

Greetings for the day. 

The simulation feature hasn't released in the edit mode. It's expected behavior.

it will appear only in the read-only mode. 

Regards, 
Vikram Kulkarni

**Comment by mounikat987** [comment] 2020-06-15 08:19
Hi @Vikramkulkarni01 ,

Yes, it's expected behaviour in read-only mode.

in Step1 ,4th instruction the screenshot has to be updated .It is still the old one which doesn't show "simulation mode" in read -only.

Actual Result : 
![oldscreenshot](https://user-images.githubusercontent.com/33411431/84633723-6fe67a80-af0e-11ea-9092-3af8cbad9b24.PNG)

Expected Result :
![newimage](https://user-images.githubusercontent.com/33411431/84633954-c3f15f00-af0e-11ea-9df0-08994c353f87.png)

Please change it in this tutorial.


Thanks
Mounika

**Comment by mounikat987** [comment] 2020-06-15 08:22
sorry...closed by mistake while adding comments

**Comment by Vikramkulkarni01** [comment] 2020-06-15 08:29
Hi Mounika, 

thanks for the update. its already in our road map and we are working towards adopting the screenshots of these tutorials to the latest one. 

You can see these changes in the coming days. 

I hope it will suffice your concern

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment] 2020-06-16 12:28
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-06-16 12:28 UTC
