### ISSUE TITLE
Set Up SAP Business Application Studio for CAP Java

### ISSUE THREAD

**Issue by Mx343** [SAPDocuments/Tutorials#5889] opened 2020-09-20 13:16 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-app-studio.html

Hello,

In step 4 of the tutorial I encounter the following problem.

When I run the command "mvn clean install" I get an error instead of the expected "BUILD SUCCESS".

[ERROR] CdsMojo: [ERROR] Cannot find module '/home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node'
Require stack:
- /home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/sqlite3/lib/sqlite3-binding.js
- /home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/sqlite3/lib/sqlite3.js
- /home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/@sap/cds-runtime/lib/sqlite/Service.js
- /home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/@sap/cds/lib/srv/factory.js
- /home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/@sap/cds/lib/srv/connect.js
- /home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/@sap/cds/lib/index.js
- /home/user/projects/products-service/node_modules/@sap/cds-dk/bin/deploy/index.js
- /home/user/projects/products-service/node_modules/@sap/cds-dk/bin/cds.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)

[ERROR] 
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at com.sap.cds.maven.plugin.util.ProcessExecutor.executeAndGetResult (ProcessExecutor.java:98)
    at com.sap.cds.maven.plugin.build.AbstractNodejsMojo.execute (AbstractNodejsMojo.java:100)
    at com.sap.cds.maven.plugin.build.CdsMojo.executeCds (CdsMojo.java:87)
    at com.sap.cds.maven.plugin.build.CdsMojo.executeViaLifecycle (CdsMojo.java:140)
    at com.sap.cds.maven.plugin.build.CdsMojo.execute (CdsMojo.java:66)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for products-service parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] products-service parent ............................ SUCCESS [  2.926 s]
[INFO] products-service ................................... FAILURE [ 13.664 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.876 s
[INFO] Finished at: 2020-09-20T13:10:42Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.sap.cds:cds-maven-plugin:1.9.0:cds (cds.build) on project products-service: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :products-service

I did the steps of the tutorial and also I'm using a trial account.
Any hints what the problem and the solution could be?

BR
Fabian

**Comment by maxstreifeneder** [comment] 2020-09-21 09:01
@iwonahahn Hi Iwona, could you please have a look? :)

**Comment by iwonahahn** [comment] 2020-09-30 07:30
Hi @Mx343,

Sorry for the late reply. I forwarded the request to the development colleagues and will get back to you asap.

Best regards,
Iwona

**Comment by beckermarc** [comment] 2020-09-30 07:34
Hi @Mx343,

can you please reproduce the issue and provide the full build log by running this command:
`mvn clean install -X > build-output.log`. Please attach the `build-output.log` to this issue for further investigation.

Best regards,
Marc

**Comment by Mx343** [comment] 2020-10-01 06:17
Hi @beckermarc ,

I run the command you provided in my already existing project and didn't start with the tutorial from scratch again (I hope this was ok).
Please see the attached build-output.log file.



[build-output.log](https://github.com/SAPDocuments/Tutorials/files/5309795/build-output.log)

Best regards,
Fabian

**Comment by beckermarc** [comment] 2020-10-01 07:31
It looks like something went wrong during installation of the `@sap/cds-dk` module. It has a dependency to the `sqlite` npm module, which brings some binary artifacts. Those need to match the Node.js version. In your build Node.js version `12.16.1` is using for which the correct binary artifacts would be under `sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node`.

Can you please check which folders can be found under: `/home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/sqlite3/lib/binding/`?

After that can you try to delete the `node_modules` folder, run `npm cache clean` and retry the build?

**Comment by Mx343** [comment] 2020-10-01 11:07
the following folders could be found in the /home/user/projects/products-service/node_modules/@sap/cds-dk/node_modules/sqlite3/lib/binding/ path.

node-v64-linux-x64 with the artifact node_sqlite3.node .

I deleted the folder node_modules `/home/user/projects/products-service/**node_modules**/@sap/cds-dk/node_modules/sqlite3/lib/binding/` and try to run the comand `npm cache clean`.
After an error I retried it with the command `npm cache clean --force` and retry the build 
This time it worked.
`[INFO] Reactor Summary for products-service parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] products-service parent ............................ SUCCESS [  7.178 s]
[INFO] products-service ................................... SUCCESS [ 54.720 s]`

I also did the `mvn clean spring-boot:run` and it worked also.

Thank you very much and best regards
Fabian

**Comment by MichaelCzcz** [comment] 2020-10-12 07:02
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-10-12 07:02 UTC
