### ISSUE TITLE
Access the SAP Screen Personas Training System

### ISSUE THREAD

**Issue by juldea** [SAPDocuments/Tutorials#5218] opened 2020-05-26 13:56 UTC
Tutorial URL: https://developers.sap.com/tutorials/personas-access-learning-sys.html

The link to the system doesnt work.

Thank you for your help
Julien déat
![2020-05-26_15h54_42](https://user-images.githubusercontent.com/61805681/82909207-410d6200-9f69-11ea-8f7e-468bb2e72a04.png)
![2020-05-26_15h55_55](https://user-images.githubusercontent.com/61805681/82909332-6c904c80-9f69-11ea-8fbd-61ebdf348f89.png)

**Comment by MichaelCzcz** [comment] 2020-05-27 07:45
I have just checked the link and it is working. Please try again.


![image](https://user-images.githubusercontent.com/57144076/82991970-c3943100-9ffe-11ea-922e-474637bae0f8.png)

**Comment by cjbernal** [comment] 2020-05-27 14:27
Hi Michael,

I have also doubled checked the link and can confirm that it is working as intended.

Kind regards,
Conrad

**Comment by MichaelCzcz** [comment] 2020-05-28 08:13
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-05-28 08:13 UTC
