### ISSUE TITLE
Develop a Fiori Launchpad App with Your Own Dev Tools

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5118] opened 2020-05-10 17:29 UTC
Mission URL: https://developers.sap.com/mission.sapui5-cf-launchpad.html

Well, this tutorial have a lot o issues:

In **Tutorial 7 - Display Data from the Northwind Service** Step 5 Redirect traffic to data source

- I think that "welcomeFile" : "/cp.portal" is wrong, at least it doesn't work for me because I get "SiteNotFound" when I do.

- This ui5.yaml is TOO sensitive, you must to respect the identation or it will not work.

- **The favorite button**, try to choose one product as favorite and try to navigate to other products, for now on all products are favorites !!! 

In **Tutorial 8 Step 6 Add hierarchy information** it's state to put the code what I think is only PART of it after the _model_ section, it's doesn't work for me, I tried many combinations and the only one that worked for me is to add this is code right after "sap.ui5" declaration (too sensitive too).

```
      "ShellUIService": {
        "factoryName": "sap.ushell.ui5service.ShellUIService",
        "lazy": false,
        "settings": {
          "setTitle": "auto"
        }
      }
    }
```
In **The Tutorial 9 - Deploy the Fiori App to Cloud Foundry**... this is hell !!!
- **I can't deploy this project more than once, if try i get a lot of issues.**
- **Step 1: Build the projetct** - I can build the MTA file but there is no log to see errors and there are errors.

- **Step 2: Deploy the built archive** - I was able to a sucessful deployment only once and never again, I try to redo this tutorial a lot of times and is always the same, I get errors with <component>_deployer. I try to change the memory/disc parameters and I try to a lot of stuff I read on internet but nothing !!!

**Comment by IObert** [comment] 2020-05-11 13:40
I'm sorry that you faced so many issues during the tutorial. This shouldn't happen! I'm not sure if I can solve all the points you mentioned but I can definitely comment on all points :) 

> I think that "welcomeFile" : "/cp.portal" is wrong, at least it doesn't work for me because I get "SiteNotFound" when I do.

This is not wrong, `cp.portal` is the right value for this property. I assume it didn't work because the "Portal deployed" app failed in your case. The link to this location won't work if that task is not completed successfully.

> This ui5.yaml is TOO sensitive

I feel your pain. YAML is quite nice to read but writing can be horrible. If you do edit this file often, I definitely recommend using VS Code plugins to make your life easier like <https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml> or <https://sap.github.io/ui5-tooling/pages/Configuration/#validation-ide-support>
I didn't want to include too many non-ui5 things into the tutorial but maybe I should add these tools.

> The favorite button...

The button is not supposed to do anything but being a toggle button (as there is no real controller logic associated with the control). It's basically just a dumb switch for now. I'll add this remark to the tutorial to avoid confusion, thanks.

>  Add hierarchy information

You can add this new section at any "child position" of the sap.ui5 node. I'm not sure why it didn't work after the "models" property. Maybe the `ShellUIService` node was attached to the wrong parent node? JSON is the other industry-standard config-approach next to YAML. In this case, writing it is earlier but reading is harder. 
If you do these tasks often, you can leverage another IDE extension to be supported during editing <http://json.schemastore.org/ui5-manifest>

> Step 1: Build the project 

So you're saying the build works fine, right?

> Step 2: Deploy the built archive 

This problem has already been addressed in #5108 and #5115


I hope I could help

**Comment by iMilazzo** [comment] 2020-05-12 03:20
Thank you for the enlightment !!

**Comment by IObert** [comment] 2020-05-12 07:44
Awesome! Does this mean the issue is resolved for you? If so, please go ahead and close the issue.

**Closed** 2020-05-12 13:14 UTC
