### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by lambavikas** [SAPDocuments/Tutorials#3026] opened 2019-02-01 18:20 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-03-add-database.html

In the step 1 I encountered the error that was mentioned by you and the fix works. But there is no explanation provided fro what is the meaning of this error, why it occurred and how does the fix resolve it.

I would really appreciate if you can provide some details around this too?

**Comment by Apfohlmann** [comment] 2019-02-11 14:06
Hi @lambavikas,

thank you for asking the question. 
This error is caused by a mismatch of an old HANA instances provided on CF trial and the static templates that generate version references to newer HANA versions.

Best regards,
André

**Comment by thecodester** [comment] 2019-02-25 11:21
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2019-02-25 11:21 UTC
