### ISSUE TITLE
Debug Your SAPUI5 App with SAP Web IDE

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#3485] opened 2019-05-12 11:05 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-debug.html

Please specify the step you are referring to

Step 4.3:
Opening the app is a bit mode complex than clicking the open button. the app's url needs to be built. clicking the Open button provides the base url + "/" + add the app id from the manfiset json (without '.') + /index.html

**Comment by IObert** [comment] 2019-05-13 08:04
Thanks @raz-korn.
You are right. This step is necessary when you use the html5 app repo service (which probably happened bc of [this wizard](https://github.com/SAPDocuments/Tutorials/issues/3484)).
I'll close this issue since most users won't run into this when you follow the tutorial.

PS: I'm glad that you were able to "figure out" the correct solution. Personally, I think you learn more of a tutorial when you don't stick 100% to the guidelines. Similar to riding your skis off-piste ⛷.
**About the actual issue**: The problem is not the `Open` link, but the configuration of the app router (`xs-app.json`). The dev team is aware of this issue and it should be fixed in one of the next version.

**Closed by IObert** 2019-05-13 08:04 UTC
