### ISSUE TITLE
Deploy CAP Java App to SAP Cloud Platform

### ISSUE THREAD

**Issue by ramadasupuli** [SAPDocuments/Tutorials#6311] opened 2020-12-09 06:10 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-deploy-cf.html

Please specify the step you are referring to
Thank you this tutorial is useful.  How can we convert this to mta modules and configure to code pipes pipeline?.

Regards,
Rama

**Comment by iwonahahn** [comment] 2020-12-09 08:34
Hi Rama,

These GitHub issues are to resolve issues (that means., problems/errors) with the tutorials. Your question is more general and likely would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers [here](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce). You can also use this [template](https://answers.sap.com/questions/ask.html?primaryTagId=9f13aee1-834c-4105-8e43-ee442775e5ce&topics=Visual%20Studio%20Code&b=%3Cp%3E%3Cb%3EYour%20environment%20(run%20the%20following%20commands):%3C/b%3E%3C/p%3E%3Cul%3E%3Cli%3Ecds%20-v%3C/li%3E%3Cli%3Enode%20-v%3C/li%3E%3Cli%3Ejava%20-version%20(if%20applicable)%3C/li%3E%3C/ul%3E%3Cp%3E%3Cb%3ESteps%20to%20reproduce:%3C/b%3E%3C/p%3E%3Cul%3E%3Cli%3Ecommand%20line%20used%3C/li%3E%3Cli%3Eactions%20in%20IDE%3C/li%3E%3C/ul%3E%3Cp%3E%3Cb%3EAdditional%20information%20(if%20applicable):%3C/b%3E%3C/p%3E%3Cul%3E%3Cli%3Eproject%20files%3C/li%3E%3Cli%3Elogs%3C/li%3E%3Cli%3Escreenshots%3C/li%3E%3Cli%3E...%3C/li%3E%3C/ul%3E#) to provide details for your project.

Thank you and best regards,
Iwona

**Comment by MichaelCzcz** [comment] 2020-12-09 08:35
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-12-09 08:35 UTC
