### ISSUE TITLE
Deploy sample.onboarding.mta project failed

### ISSUE THREAD

**Issue by takismart** [SAPDocuments/Tutorials#4184] opened 2019-11-11 01:05 UTC
Tutorial: Set Up a Workflow With Extended Employee Onboarding
https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Step 5: Build and deploy the sample application

An error message displayed after I deploy the project:
Error executing application "uiDeployer": Deployment of html5 application content failed [Deployment Id: deploy-2ca1f165-041b-11ea-9e81-eeee0a81af07]
Stopping application "uiDeployer"...
A step of the process has failed. Retrying it may solve the issue.
To download logs of the process, use the multi-target application plug-in for the Cloud Foundry CLI command "cf dmol -i 2ca1f165-041b-11ea-9e81-eeee0a81af07" directly in your Cloud Foundry space.

What should I do to fix this issue?

Thank you very much.

**Comment by bcschaich** [comment] 2019-11-14 17:16
To solve this more information is needed. So do as the message sas and install the CFCLI and start the cf dmol command as mentioned. This will download the complete error message and hopefully there is more information. It actually deployed beyound this point for me....

**Comment by ArchanaShukla** [comment] 2019-11-26 04:28
@takismart - do you still face the issue? If yes, please attach the folder after running the command cf dmol command as mentioned. Usually the sample.onboarding build and deploy goes perfectly fine without any issue provided you have not modified it.

**Comment by ArchanaShukla** [comment] 2020-01-20 05:59
Hope the issue is resolved as we did not hear from you. 
@thecodester - please close the issue

**Closed** 2020-01-20 06:02 UTC

**Comment by manjunathgudisi** [comment] 2020-02-02 16:04
I was trying this tutorial to be executed in my SAP CP account. I had this problem. After I get this message, I went to SAP CP cockpit and clicked on **uiDeployer** and clicked on **Start** button manually. Then it status changed to **Started**.
