### ISSUE TITLE
Create a Simple ABAP CDS View in ADT - Screenshot in Step 5

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#3625] opened 2019-06-13 13:27 UTC
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html

Please specify the step you are referring to

The screenshot in step 5 shows the fields currency_code and gross_amount without the qualifier sepm_sddl_so_invoice_item they were shown in step 2.

For consistency's sake it might be best to show them the same way throughout the exercise.

Thanks & Cheers
Bärbel

**Comment by julieplummer20** [comment] 2019-06-24 06:54
Ok thanks Baerbel. I'll fix this. 
Best wishes,
Julie.

**Comment by julieplummer20** [comment] 2019-07-23 10:42
Hi Baerbel,
I've fixed this and pushed to QA. Sorry for the delay. I was ill.
Thanks for all the feedback.
Best wishes,
Julie.

**Comment by thecodester** [comment] 2019-07-24 06:06
@julieplummer20 Is this going to production?

**Comment by julieplummer20** [comment] 2019-07-24 06:49
Hi,
When I pushed to QA I got this error :

Command failed: git push origin master:refs/heads/master To https://github.com/SAPDocuments/Tutorials-Contribution.git ! [rejected] master -> master (fetch first) error: failed to push some refs to 'https://github.com/SAPDocuments/Tutorials-Contribution.git' hint: Updates were rejected because the remote contains work that you do hint: not have locally. This is usually caused by another repository pushing hint: to the same ref. You may want to first integrate the remote changes hint: (e.g., 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details.

… but now I have a deadline in another project, so unless there is a very quick fix, I can’t look into this just now.
Thanks for getting in touch tho.
Julie.

**Comment by thecodester** [comment] 2019-10-03 09:37
@julieplummer20 Has this been resolved? Can we close?

**Comment by julieplummer20** [comment] 2019-10-07 08:43
@thecodester 

Hi Daniel, Yes we can close this thanks.
Best wishes,
Julie.

**Closed** 2019-10-07 09:43 UTC
