### ISSUE TITLE
Create Custom UI for S/4HANA on SAP Cloud Platform

### ISSUE THREAD

**Issue by peterpersiel** [SAPDocuments/Tutorials#3169] opened 2019-03-04 16:54 UTC
Tutorial URL: https://developers.sap.com/tutorials/abap-custom-ui-tile.html

Images are defect

**Comment by thecodester** [comment] 2019-03-05 05:37
@mervey45 Many of the pictures are 0 bytes. Also, the QA version is much different than production -- are you in the middle of updating?

**Comment by mervey45** [comment] 2019-03-05 07:50
@thecodester This is Niloofars tutorial, but she isn't there anymore, due to her pregnancy. We had a lot of issues. When the users delete their caches, the images appear again. I don't know what the cause is. And I'm not in the middle of an updating process for this tutorial.

**Comment by thecodester** [comment] 2019-03-05 08:13
The cache issue I can take care of. 

But if you look at the images in GitHub, many are 0 Bytes, I assume the ones updated 15 days ago. Can you check why? And why is the version in QA -- at least images -- different from the version in production?

![image](https://user-images.githubusercontent.com/11659786/53790140-ebe1cc80-3f2e-11e9-8701-efbfb0c397db.png)

@mstmustisnt Can you check this out and make sure our plugin didn't do anything here?

**Comment by mervey45** [comment] 2019-03-05 08:18
@thecodester I'll check it. Maybe Niloofar did some changes.

**Comment by mervey45** [comment] 2019-03-05 09:36
@thecodester 
This is the QA folder: 
![image](https://user-images.githubusercontent.com/27953324/53795447-4cbed400-3f32-11e9-9443-d52e853aa0bb.png) 

And this is my fork:
![image](https://user-images.githubusercontent.com/27953324/53795525-7677fb00-3f32-11e9-9a93-bf762e81fb0b.png)

Should I just trigger the everything for this tutorial again?

**Comment by thecodester** [comment] 2019-03-05 09:53
@mervey45 Are you looking at abap-custom-ui-tile? From the screenshots it doesn't seem so.

**Comment by mervey45** [comment] 2019-03-05 10:02
@thecodester  Ok, I see it now. I think Ulrike Liebherr did some changes there. Should I just republish this tutorial?

**Comment by thecodester** [comment] 2019-03-05 10:08
Probably the best. Just make sure the tutorial is updated and ready to be published.

**Comment by mervey45** [comment] 2019-03-05 10:16
@thecodester Ok, I'll do that.

**Comment by thecodester** [comment] 2019-04-22 12:50
The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2019-04-22 12:50 UTC
