### ISSUE TITLE
SAML and OAuth 2 authentication

### ISSUE THREAD

**Issue by marcusthelander** [SAPDocuments/Tutorials#1755] opened 2017-06-09 08:50 UTC
Hello, thank you for a great tutorial. However, after configuring my application on SAP Mobile Service for Development and Operations and following this guide (https://www.sap.com/developer/tutorials/fiori-ios-scpms-saml-oauth.html) for SAML authentication i get the error on my mobile client saying: _"**Loading Data failed!** DataServiceError: The server responded with an SAP Cloud Security Login Request (status 200 with a custom login page). No handler/interceptor has been registered with the DataService to handle this case, so the response status has been changed to 401."_

After getting that message i would guess that the SAML authentication are fine from SCP site and the problem are that something is missing in, probably, the metadata.xml-file that i generated in the browser without any modification (in relation to this tutorial).

What is you take on that message? See attached picture of the message.

<img width="618" alt="screen shot 2017-06-09 at 10 32 36" src="https://user-images.githubusercontent.com/9093522/26967696-84cbaa84-4cff-11e7-9d15-f32515aa4ec1.png">

**Comment by qualiture** [comment] 2017-06-09 12:44
Hi @marcusthelander, could it be you have generated the application with SDK Assistant using a different (i.e. previously configured) authentication mechanism? 

For instance, if you first have created an application definition in SAP Cloud Platform mobile services (SAPcpms) with Basic Authentication, then generate an app with SDK Assistant, and then switch the authentication mechanism in SAPcpms, the generated app won't work. Reason being, the generated app takes the configuration from SAPcpms and creates the relevant Authentication class.

Can you check whether your application contains a `./ViewController/SAMLAuthViewController.swift` file?

**Comment by qualiture** [comment] 2017-11-15 09:07
Hi @marcusthelander,

If the issue is resolved, you may close it.

Thanks,
Robin

**Comment by thecodester** [comment] 2018-02-11 09:13
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2018-02-11 09:13 UTC
