### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by agl-phenr** [SAPDocuments/Tutorials#3111] opened 2019-02-19 18:59 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Please specify the step you are referring to: Step 3 - enable JTA support and container management.

There is no such folder named "gen" thus I cannot change the "persistence.xml" file.

Therefore at the statement:
import com.sap.demo.bookshop.jpa.my.bookshop.Books;
import com.sap.demo.bookshop.jpa.my.bookshop.Orders;
I see the error message: "error: JAVA: the import com.sap.demo cannot be resolved".

Best Regards,
Pietro

**Comment by JijoRoyJacob** [comment] 2019-02-20 08:04
Hi Pietro,
In **Step 1: Generate JPA classes**, sub-step 10 requires you to build the project. If this sub-step was successful, then the JPA classes in the message would have been generated, including the gen folder. You can also perform the build by right-clicking the srv folder and selecting Build. Please let me know if you got any errors when performing this step.

Best regards,
Jijo

**Comment by agl-phenr** [comment] 2019-02-20 08:43
Hi @JijoRoyJacob,

I went through all the sub-steps of step 1 and at the end a rebuilt the whole project.

![image](https://user-images.githubusercontent.com/42214365/53077354-b3cb9a00-34e9-11e9-93e3-29cb6d684bbe.png)

Right-clicked the main root folder and refreshed the workspace but even so I see no gen folder.

![image](https://user-images.githubusercontent.com/42214365/53077566-2472b680-34ea-11e9-9192-1ea08ac182e3.png)

I have attached the whole project in case you might see something wrong or missing.

Best Regards,
Pietro

[bookshop.zip](https://github.com/SAPDocuments/Tutorials/files/2883711/bookshop.zip)

**Comment by JijoRoyJacob** [comment] 2019-02-20 09:52
Hi Pietro,
I checked your project and cannot see the root cause of the problem. I'll share the project with the dev team and I'll get back to you on what I learn from them.

Best regards,
Jijo

**Comment by JijoRoyJacob** [comment] 2019-03-11 08:27
Hi Pietro,
Sorry for the late response. The dev team colleague, I was following up with, could not replicate and also could not determine the cause of the issue you're facing. I created a brand new project followed the JPA tutorial and I was able to see the gen folder and all the succeeding steps worked as well. Kindly retest with a new project and please let me know if you still see the issue. If you still face the issue, please let me know the environment you're testing in (trial or productive).

Best regards,
Jijo

**Comment by benuantony** [comment] 2019-03-17 17:15
Hello Jijo,

I had struck up with the same issue mentioned by Pietro during the build. (step 10 of Use JPA in Custom Logic)

import com.sap.demo.bookshop.jpa.my.bookshop.Books;
import com.sap.demo.bookshop.jpa.my.bookshop.Orders;
I see the error message: "error: JAVA: the import com.sap.demo cannot be resolved".

There is something missing or misleading in the documentation.

Regards,
Benu

**Comment by JijoRoyJacob** [comment] 2019-03-18 02:53
Hi Benu,
Are you testing this from your trial account?

Best regards,
Jijo

**Comment by TuncayKaraca** [comment] 2019-04-05 15:11
Hi Jiyo,

I have exactly the same issue that Pietro and Benu have. For me yes I use my trial account.
There is something missing here. Appreciate any guidance.

Thanks,
Tuncay

**Comment by JijoRoyJacob** [comment] 2019-04-09 09:04
Hi Tuncay,
The order of steps listed is important. In Benu's case, we found that the order wasn't followed and so the JPA classes never got generated as part of Step 1. If you successfully execute step 1, you should be able to see the following files in the path indicated:

![JPA](https://user-images.githubusercontent.com/41678923/55787284-8ce61900-5ad3-11e9-80b4-251a66c09a41.png)

Try starting from scratch: 
1. [Create a new bookshop app](https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html)
2. [Add the database](https://developers.sap.com/tutorials/cp-apm-03-add-database.html)
3. [Add Custom Logic](https://developers.sap.com/tutorials/cp-apm-04-custom-logic.html)
4. [Follow the JPA tutorial](https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html). Pay special attention to Step 1.

Hope this helps.

Best regards,
Jijo

**Comment by balajii7** [comment] 2019-05-02 20:13
Hi Jijo,
There is definitely something missing in steps. Initially in the Step 1, I was not able to build successfully with the below error:
![image](https://user-images.githubusercontent.com/7418651/57103733-da4a5480-6d26-11e9-9b13-0def8b958a18.png)
So I re-ran Maven with -X and enabled full debug logging. After that I have executed the Maven Goal 'generate-resources' and then the source directory /src/gen/java has been added and the build was successful:
![image](https://user-images.githubusercontent.com/7418651/57103933-5cd31400-6d27-11e9-9a3a-dfabde9cd164.png)

Regards,
Sai

**Comment by balajii7** [comment] 2019-05-02 20:34
But my project build still fails. Please let me know what am I missing. I'm at the step 1 and followed all the steps in the sequence.
![image](https://user-images.githubusercontent.com/7418651/57105106-424e6a00-6d2a-11e9-9f81-95684695f54e.png)

**Comment by JijoRoyJacob** [comment] 2019-05-03 06:23
Hi Sai,
Kindly share your project so that I can take a look. And please let me know which environment you're testing this in.

Best regards,
Jijo

**Comment by balajii7** [comment] 2019-05-03 07:16
Hi Jijo,
Thanks for the response. I have invited you to the project and here is the link: https://github.com/balajii7/scp-demos/invitations
Regards,
Sai

**Comment by JijoRoyJacob** [comment] 2019-05-03 07:33
Hi Sai,
I noticed that in srv/pom.xml, the dependencies are listed under the <profile> tag. It should be listed outside the <profile> tag. Kindly refer the screenshot and folder structure in the tutorial for more details. Rerun the build after making the changes.

Best regards,
Jijo

**Comment by balajii7** [comment] 2019-05-03 07:48
Hi Jijo,
I have made changes to the pom.xml, sorry for that mistake. But the build still fails with the below error:
![image](https://user-images.githubusercontent.com/7418651/57125146-8d976580-6d88-11e9-8771-8c6b09e331d7.png)

Regards,
Sai

**Comment by JijoRoyJacob** [comment] 2019-05-03 08:06
Hi Sai,
I see that you have these two additional dependencies `slf4j-api` and `ngdbc` specified in pom.xml. In the JPA tutorial, I have mentioned three dependencies that you'll need. I'm not sure about these two.  If its not needed for your project, remove them (at least ngdbc) and try building again.

Best regards,
Jijo

**Comment by balajii7** [comment] 2019-05-03 08:11
Hi Jijo,
I guess those additional dependencies were there when the project has been created, and I left them as is and added the other dependencies as mentioned in the tutorial. I removed them and the build is successful. Thanks a lot for the help. 
Regards,
Sai

**Comment by thecodester** [comment] 2019-05-05 05:25
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2019-05-05 05:25 UTC
