### ISSUE TITLE
Build an SAP Fiori app with SAP Gateway data in SAP Web IDE

### ISSUE THREAD

**Issue by Mohanmk1** [SAPDocuments/Tutorials#3135] opened 2019-02-23 07:18 UTC
Tutorial URL: https://developers.sap.com/tutorials/teched-2016-4.html

Please specify the step you are referring to step 19, 
getting error HTTP Status 404 - Not Found

![image](https://user-images.githubusercontent.com/28388659/53283244-42018380-3769-11e9-867f-6056773a4639.png)

**Comment by thecodester** [comment] 2019-02-24 06:42
Is this in trying to click Validate? Can you try again ... it is working for me currently

**Comment by kjetil-kilhavn** [comment] 2019-02-25 19:43
I get the same error (although with /SAP_Gateway/ as the first part of the requestUri).

**Comment by kjetil-kilhavn** [comment] 2019-02-25 20:24
And by trial and error I found something that worked. The same approach should proably work for you @Mohanmk1  - and once you confirm @thecodester can either update the tutorial or add a "if you get a 404 response, try..." section or comment.

I went back to the 'neo-app.json' file and tried different combinations of 'path' and 'entryPath'.
When I prefixed 'path' with my system name it worked, i.e. in my case 
 {
      "path": "SAP_Gateway/sap/opu/odata",
      "target": {
        "type": "destination",
        "name": "SAP_Gateway",
        "entryPath": "sap/opu/odata"
      },
      "description": "SAP Gateway ES5"
    }
Party on ... or rather, now I can continue with the next step in the tutorial.

**Comment by Mohanmk1** [comment] 2019-02-27 06:55
@kjetil-kilhavn, Thanks for your help, i have followed your instruction its work fine for me. one more point to add. when i used the code in step17 also work fine.
    {
      "path": "/ES5",
      "target": {
        "type": "destination",
        "name": "ES5"
      },
      "description": "SAP Gateway ES5"
    }
now i can continue with the next step.

**Comment by mts2605** [comment] 2019-03-15 19:25
Perfect assistance here.
When my file was changed to like below - it all worked!
_
    {
      "path": "SAP_Gateway/sap/opu/odata",
      "target": {
        "type": "destination",
        "name": "SAP_Gateway",
        "entryPath": "sap/opu/odata"
      },
      "description": "SAP Gateway ES5"
    }
  ],

**Comment by thecodester** [comment] 2019-03-17 06:04
@Mohanmk1 If the issue is resolved, please close the issue.

**Closed** 2019-04-16 10:55 UTC
