### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#7166] opened 2021-11-09 07:20 UTC
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

Step 3: Copy credentials from service key : The default instance name that the booster provides is 'default-it-rt-integration-flow'
Please update the sentence in the tutorial accordingly.
Expected:
![image](https://user-images.githubusercontent.com/50734023/140879021-7b0f2c1d-c79f-410e-a723-a9e5e5faf472.png)

Actual:
![image](https://user-images.githubusercontent.com/50734023/140879328-29ba76bb-0607-4a07-aba8-2923e225f063.png)

**Comment by Karunaharan** [comment] 2021-11-09 08:58
@NidhiMurkute - the issue is fixed. will publish as soon as I have other feedback from your entire testing.

**Comment by Karunaharan** [comment] 2021-11-09 09:00
@NidhiMurkute - the issue is fixed. will publish as soon as I have other feedback from your entire testing.

**Comment by Karunaharan** [comment] 2021-11-09 10:21
@MichaelCzcz - I'm not able to close the issue which I used to do in the past. Could you please check why am I not able to close?

**Closed** 2021-11-09 10:24 UTC
