### ISSUE TITLE
Set Up Process Visibility to Track Employee Onboarding Workflow

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#5148] opened 2020-05-14 04:57 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html

In Step 1 in screenshot the tile is configure business scenario but in app showing configure Visibility scenario

**Comment by ArchanaShukla** [comment] 2020-05-18 05:25
This is expected. That is coming from the product itself and how the the tiles have been recommended to be configured. Will request the product documentation to be changed appropriately.

**Comment by ArchanaShukla** [comment] 2020-05-20 05:14
I have been confirmed by the dev team that this is fixed. If you re-deploy the BPMServicesFLP then the issue would not be there any more. @MichaelCzcz  - Please close the ticket

**Comment by MichaelCzcz** [comment] 2020-05-20 13:35
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-05-20 13:35 UTC
