### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by agl-phenr** [SAPDocuments/Tutorials#4431] opened 2020-01-03 13:15 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Please specify the step you are referring to Step 05 - Test the application

Hi,
I manage to get the app deployed to the CF trial, however, by accessing the endpoint I got issue HTTP ERROR 502.
In attachments, you find the app log.

[java app running - log.txt](https://github.com/SAPDocuments/Tutorials/files/4019200/java.app.running.-.log.txt)
[java app running2 - log.txt](https://github.com/SAPDocuments/Tutorials/files/4019201/java.app.running2.-.log.txt)

Would someone give me a help?

BR,
Pietro

**Comment by renejeglinsky** [comment] 2020-01-07 14:52
Hi Pietro,

Do you still have this issue? If yes, could you share your project with me? Could you also share the link to your application? 

Regards,
René

**Comment by agl-phenr** [comment] 2020-01-07 16:18
Hi @renejeglinsky ,

I am still getting the same issue.

Find enclosed the project: 
[bookshop.zip](https://github.com/SAPDocuments/Tutorials/files/4031459/bookshop.zip)

the link is: https://mhvffewfsbeiiq8g-bookshop-srv.cfapps.eu10.hana.ondemand.com/

BR,
Pietro

**Comment by renejeglinsky** [comment] 2020-01-09 12:31
Hi,

let's try something:
Please go into your space in the Cloud Cockpit, open your application there and click on the link in the "Application Routes" section?

Let me know if this workaround works for you. Thanks.

René

**Comment by agl-phenr** [comment] 2020-01-09 12:40
Hi @renejeglinsky,

I tried out, and I got the same issue (HTTP 502).
I am not sure if it might be relevant, but I am using SAP Web IDE in a non-trial account (my company's) but deploying to CF trial (as my company´s CF misses some services required in this tutorial).

**Comment by renejeglinsky** [comment] 2020-01-09 19:24
Hi @agl-phenr ,

I guess this is not the issue. I'll reach out to my colleagues. I am not sure what the issue is in this case. I can reproduce it. I'll keep you posted. Thanks for your patience.

-René

**Comment by MichaelCzcz** [comment] 2020-03-02 08:00
Hello @renejeglinsky. Any updates?

**Comment by renejeglinsky** [comment] 2020-04-07 07:36
This tutorial is out of maintenance and already removed from the platform. It can be closed.

**Comment by MichaelCzcz** [comment] 2020-04-09 06:41
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-04-09 06:41 UTC
