### ISSUE TITLE
MovieLens with SAP HANA APL Recommendation (MovieLens App) - Build of db failed. Check console logs for details

### ISSUE THREAD

**Issue by mavesura** [SAPDocuments/Tutorials#2808] opened 2018-11-26 08:29 UTC
[movielens_db_failed.txt](https://github.com/SAPDocuments/Tutorials/files/2614589/movielens_db_failed.txt)
While building db, am getting the error as attached. Request you to kindly look into and provide work around to proceed further.
The tutorial is : MovieLens with SAP HANA APL Recommendation (MovieLens App)

Thanks, Mave.

**Comment by adadouche** [comment] 2018-11-28 16:35
Hi @mavesura 

I think that this issue is caused by the fact that you don't have the APL installed on your SAP HANA, exppress edtion.

cf [issue)(https://github.com/SAPDocuments/Tutorials/issues/2809)

**Comment by adadouche** [comment] 2018-12-03 09:14
Hi @mavesura 

I'll close this issue for now, as it seems that your APL installation is not complete and therefore you won't be able to finish this tutorial.

Regards

@bdel

**Closed by adadouche** 2018-12-03 09:14 UTC
