### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5670] opened 2020-08-11 06:43 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to : Step 8: Test integration flow using Postman      
4.Getting 500 internal server error when post request is made.
Region : EU

Expected:
![image](https://user-images.githubusercontent.com/50734023/89865732-e41a6300-dbcb-11ea-8e8a-7458b63c5e21.png)

Actual:
![image](https://user-images.githubusercontent.com/50734023/89865766-f5fc0600-dbcb-11ea-8d5c-9946a4287a0c.png)

Regards,
Nidhi

**Comment by Vikramkulkarni01** [comment] 2020-08-17 09:52
Hi Nidhi, 

Thanks for reaching out to me via this channel. 

From the screenshot, I understand that you are getting an internal server error. 

Please ensure that you have followed other steps and fulfilled the pre-requisite accordingly. 

The error occurring could be a problem on the server-side. A server error can be caused by any number of things,
1. Reload the web page.
2. Clear your browser's cache.
3. Delete your browser's cookies.

Let me know if the issue is persisting still. 

Regards, 
Vikram Kulkarni

**Comment by gramman75** [comment] 2020-08-26 00:24
Hi 

at step8: postman request url
i response 403 forbidden.

![image](https://user-images.githubusercontent.com/1618203/91240817-f4ab0b80-e77d-11ea-9688-cd73598738ec.png)

**Comment by Vikramkulkarni01** [comment] 2020-08-26 03:41
Hi @gramman75, 

Thanks for reaching out to me. 

This generic error indicates you have got a response from server for the request you made but refuses to authorize it. 

Could you please check authorization once again? and run the scenario again.

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment] 2020-08-31 09:42
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-08-31 09:42 UTC
Labels: SCPTest
