### ISSUE TITLE
Count is not changing in the Process Workspace App in AP21 Region

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6113] opened 2020-11-04 17:22 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Steps: 
**1. Step 5: View process visibility workspace
2. Step 7: View process visibility workspace for completed workflow**

In Step 5, in **Monitor Visibility Scenarios app** when we click on Process data(2nd time), the Events and Instances processed is **zero** **in Ap21 region** as below.
![image](https://user-images.githubusercontent.com/65999547/98143765-86a66180-1eef-11eb-89b4-ed0e50b83eca.png)
So when we open the **Process workspace**, the number of **open instances is not changed** and remains same.

Similarly in Step 7 as well, when we click on Process data(3rd time), the Events and Instances processed is zero again.
So in the Process workspace, the number of **Completed Instances also remain unchanged.**

Labels :
Landscape Labels: trail3
SCPTest-eboard: Automate and Extend Employee Onboarding
Priority label :‘High-prio’

Best Regards,
Priyanka

**Comment by ArchanaShukla** [comment] 2020-11-05 12:36
Hello Priyanka, 
The number wont change until you have any new process events. Also, it might take sometime to process the events. Did you tried 1-2 times. Is the workflow completed - did you confirmed it from Monitor Workflow app?

**Comment by PriyankaShivakumar** [comment] 2020-11-05 13:18
Hi Archana,

I tried it multiple times, the number of processed events and instances remained zero in the AP21 Region.
I also checked the Monitor Workflow - Workflow Instances app and the workflow was completed.

Note: I rechecked the same flow in EU10 region and here the scenario was working as expected. 

Best Regards,
Priyanka

**Comment by ArchanaShukla** [comment] 2020-11-05 13:42
Can you please raise a ticket on LOD-BPM-PVS component, looks like a product issue.

**Comment by PriyankaShivakumar** [comment] 2020-11-06 06:25
Hi Archana,
I have retested the scenario on AP21 region today and this issue seems to be a temporary one as the scenario is working as expected now.
Please close the ticket.
Best Regards,
Priyanka

**Comment by MichaelCzcz** [comment] 2020-11-09 12:00
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-11-09 12:00 UTC
Labels: High-Prio, SCPTest-2009A, SCPTest-eboard, SCPTest-trial3
