### ISSUE TITLE
.Deploy Application to Cloud Foundry with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by jake-barry** [SAPDocuments/Tutorials#4559] opened 2020-01-30 19:01 UTC
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-deploy-application-cloud-foundry.html

CI build scripts are not included.

First step in this tutorial fails after doing the previous tutorials:

my-sdk-project$ > npm run ci-build
npm ERR! missing script: ci-build
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     prebuild
npm ERR!     build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2020-01-30T18_56_19_619Z-debug.log
my-sdk-project$ >

# package.json

{
  "name": "my-sdk-project",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint '{src,apps,libs,test}/**/*.ts' --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^6.10.14",
    "@nestjs/config": "^0.1.0",
    "@nestjs/core": "^6.10.14",
    "@nestjs/platform-express": "^6.10.14",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^6.5.4"
  },
  "devDependencies": {
    "@nestjs/cli": "^6.13.2",
    "@nestjs/schematics": "^6.8.1",
    "@nestjs/testing": "^6.10.14",
    "@types/express": "^4.17.2",
    "@types/jest": "^24.0.25",
    "@types/node": "^13.1.6",
    "@types/supertest": "^2.0.8",
    "@typescript-eslint/eslint-plugin": "^2.12.0",
    "@typescript-eslint/parser": "^2.12.0",
    "eslint": "^6.7.2",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-import": "^2.19.1",
    "jest": "^24.9.0",
    "prettier": "^1.18.2",
    "supertest": "^4.0.2",
    "ts-jest": "^24.3.0",
    "ts-loader": "^6.2.1",
    "ts-node": "^8.6.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^3.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

**Comment by mr-flannery** [comment] 2020-02-03 10:21
Is this a duplicate of #4558 ?

**Comment by MichaelCzcz** [comment] 2020-02-10 09:40
@jake-barry this seems to be a duplicate. I am closing it. Please feel free to reopen it should I be wrong.

**Closed by MichaelCzcz** 2020-02-10 09:40 UTC
