### ISSUE TITLE
Install the Optional SAP HANA Automated Predictive Library Package for SAP HANA, express edition

### ISSUE THREAD

**Issue by mavesura** [SAPDocuments/Tutorials#2809] opened 2018-11-26 11:10 UTC
Cannot being able to run the install_apl.sh script.. 

We need to run as root and don't have access to root

**Comment by i067268** [comment] 2018-11-27 11:32
@mavesura 
do you mean,  you can not run the install_apl.sh script because you don't have root permission, and this script need run as root, right?

**Comment by adadouche** [comment] 2018-11-28 16:34
Hi @mavesura 

do you have sudo rights ? I mean that you should get access to the hxeadm user, which by default have sudo rights.

Regards
@bdel

**Comment by adadouche** [comment] 2018-12-03 09:13
Hi @mavesura 

Have you been able to complete the APL installation?

Thanks

@adadouche

**Comment by adadouche** [comment] 2018-12-14 04:05
Hi @mavesura ,

I hope that "no news is good news". I'll close this issue for now, but feel free to reopen if the issue is not solved.

Thanks
@

**Closed by adadouche** 2018-12-14 04:05 UTC
