### ISSUE TITLE
Create Cards with Actions (Like Approve Or Reject)

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#3337] opened 2019-04-10 04:47 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Hello @jitendrakansal  , 
I am trying to add parameter in Mobile cards as per step 2 but it is giving me below error :

**Global parameters cannot have a JSON path as value.**

One more thing when I go to URLs tab , it always shows error 'A Query URL does not return data. Use one of the other URLs instead to show data.'  in Data section. This was not the case earlier. I saw proper JSON response when I worked on Mobile cards 4 months ago.

Please check where am I going wrong.

Regards,
Amit

**Comment by jitendrakansal** [comment] 2019-04-10 07:43
@amitcruz i am able to reproduce this issue, will check internally and get back. thanks for notifying.

**Comment by amitcruz** [comment] 2019-04-11 04:25
@jitendrakansal  Thanks for acknowledging , I am looking forward for the quick solution.

**Comment by jitendrakansal** [comment] 2019-04-29 06:34
tutorial has been updated with latest change in MS cockpit UI. Pls give a try now. 

regarding error 'A Query URL does not return data. Use one of the other URLs instead to show data' , pls ignore it , we will fix it in future release.

**Comment by thecodester** [comment] 2019-05-06 08:29
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by thecodester** 2019-05-06 08:29 UTC
