### ISSUE TITLE
XS Advanced development - Configure a Space to develop on a tenant database

### ISSUE THREAD

**Issue by Vest** [SAPDocuments/Tutorials#2255] opened 2018-03-03 12:22 UTC
Would it be possible to add a link to the tutorial/documentation that describes how to use multiple tenants in the development environment?
My major concern is regarding this sentence: **You can now use the space in your Multi Target Applications.**
There are no links telling me what will happen, if I choose two or more tenants per space. If I deploy CDS artifacts, where they will be and so on.

thank you, if you can update the tutorial.

**Comment by Lsubatin** [comment] 2018-03-06 21:33
Hi Vest, 

To which documentation do you refer? You cannot choose more than one tenant per space simultaneously and I would generally not recommend switching the tenants in spaces as you would need to recreate some services manually.

How to set a space in an MTA app is described in the very first basic tutorial for XSA development: https://www.sap.com/developer/tutorials/xsa-connecting-webide.html

Please clarify what the concern is about.

Thanks, 
Lucia.

**Comment by Vest** [comment] 2018-03-07 11:27
Thank you for your reply Lucia, here is what I faced with:

In SAP HANA Service Broker you can choose the SPACE and assign the tenant to it. Here is the screenshot from my system:
![Map the existing SPACE](https://i.imgur.com/2A1SXVU.png)

In my example, I was able to add another tenant, and make it "default":

![Add another tenant](https://i.imgur.com/ytkZEL0.png)

I raised the issue, because I understood how tenants can be assigned to the SPACE, but from the code/config it is unclear how to switch between tenants.

I will appreciate your help, if you can update the tutorial with this information.

Vest

**Comment by Lsubatin** [comment] 2018-03-07 20:38
Hi, Vest, why would you assign multiple tenants to the same space? I can only see complications with that approach, as the default will be used unless you explicitly state something different in the containers when you create them.

**Comment by Vest** [comment] 2018-03-08 13:31
Hello Lucia,

Thank you for your attention. Indeed:
> why would you assign multiple tenants to the same space
I don't have the real use-case, because I found this thing, when I was reading multiple tutorials on Internet. I realized that if the software (HANA) allows you to assign logical databases (more than 1) to the same SPACE, there should be the gear in XSA to control what tenant I want to use in this particular moment.

Maybe I prefer to use different tenants for different applications that I deploy to the same SPACE instead of SCHEMAs or different SPACEs.

Am I correct that the screen above exists in HANA, but this is a useless functionality (or bug?!) that nobody ever used?
![Multiple Tenants](https://camo.githubusercontent.com/defe86514371382949ff0d69aca78b56cbdd1b19/68747470733a2f2f692e696d6775722e636f6d2f79746b5a454c302e706e67)

Thanks,
Vest

**Comment by Lsubatin** [comment] 2018-03-08 13:56
As the saying goes, it's not a bug, it's a feature! 

I cannot find a scenario for this. Cross-tenant access is possible but it's only in very specific scenarios that you need it and you would not achieve that by assigning multiple tenants to the same space.

I associate spaces to specific projects for example, they allow you to have different teams working on the same resources and have the same people with different roles or permissions across different spaces. 

 The hdi-containers (managed schemas with  their own technical users) will be the ones pointing at the tenant. The parameter would be there or it would take whatever is set to default in the space when the service is created but no one would know which tenant is behind that.

Although I found the discussion interesting, this certainly does not belong here, so closing the issue.

Cheers, 

Lucia.

**Closed by Lsubatin** 2018-03-08 13:56 UTC

**Comment by Vest** [comment] 2018-03-08 14:34
Ok, thank you for your time, Lucia.
I will try to find somewhere else then, how to create HDI containers for different tenants within the same SPACE, as this tutorial doesn't cover this topic, as well as don't tell where to go further.

Warm regards,
Vest

**Comment by Lsubatin** [comment] 2018-03-08 23:14
Sure... for the record and to summarize, i think that configuration is a bad idea.

**Comment by chillamcherla** [comment] 2018-09-27 17:42
how can we connect / switch form one space to another suing XSA CLI,
