### ISSUE TITLE
Deploy Your First SAPUI5 App to Cloud Foundry

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#4916] opened 2020-04-10 08:41 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-new-app.html

Please specify the step you are referring to

Step 4: Build the application

I received the following error when trying to complete this tutorial. I even went to the Entitlements and added the Connectivity runtime but still had an error building this "tutorial" application. 

Service "uaa_tutorial" exists but doesnt have any bound applicationsProcessing service "dest_tutorial"...Creating service "dest_tutorial" from MTA resource "dest_tutorial"...Service operation failed: Controller operation failed: 404 Updating service "dest_tutorial" failed: Not Found: Error creating service "dest_tutorial" from offering "destination" and plan "lite": Could not create service instance "dest_tutorial". Service plan "lite" from service offering "destination" was not found. Processing service "uaa_tutorial"...Setting service "uaa_tutorial" parameters from "xs-security.json"To download the process logs, use the "cf dmol -i 2a65db7d-7b06-11ea-904d-eeee0a852e19" command in the Cloud Foundry CLI directly in your Cloud Foundry space.See https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e93b231895b64cbc9221a62953563a6f.html.Job failed.
6:35:16 PM (DeploymentToCF) Deployment of the "tutorial" project failed.(Response state is FAILED)

Please assist.

Thanks & Kind Regards
Phil Cooley

**Comment by pjcools** [comment] 2020-04-10 08:42
Sorry the issue is with Step 5: Deploy the archive to Cloud Foundry.

**Comment by IObert** [comment] 2020-04-14 15:30
Hi Phil,

that issue sounds like there is something wrong with your entitlements. Can you please follow this [tutorial](https://developers.sap.com/tutorials/cp-cf-entitlements-add.html) to make sure your account is set up correctly?

**Comment by pjcools** [comment] 2020-04-16 09:28
Hi Marius

I updated my entitlements and the same issue occurs when trying to deploy to Cloud Platform. I even added the Destination entitlement?? 

Same issue. 

Service operation failed: Controller operation failed: 502 Updating service "dest_tutorial" failed: Bad Gateway: Error creating service "dest_tutorial" from offering "destination" and plan "lite": CF-ServiceBrokerRequestRejected(10001): Service broker error: service plan not found or not accessible To download the process logs, use the "cf dmol -i 8785c5c3-7fc4-11ea-a2dc-eeee0a8724e5" command in the Cloud Foundry CLI directly in your Cloud Foundry space.See https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e93b231895b64cbc9221a62953563a6f.html.Job failed.
7:28:17 PM (DeploymentToCF) Deployment of the "tutorial" project failed.(Response state is FAILED)

thanks
Phil

**Comment by IObert** [comment] 2020-04-16 10:29
Mhh, very strange. Do you have the CF CLI installed? If so, can you try `cf marketplace` to check if you see the service offering?
You could also try `cf create-service destination lite myDest` to check whether you can create the service instance manually

**Comment by pjcools** [comment] 2020-04-18 04:15
Yes, I installed this and ran that cf marketplace command and this is what I got back. 

Getting services from marketplace in org P028445trial_p028445trial / space dev as phil@bpsolutions.com.au...
OK

service                    plans                                           description
abap-trial                 shared                                          Access a shared instance to build custom ABAP cloud apps, leveraging newest innovations powered by SAP HANA.
api-management             lite                                            Expose your data and processes as APIs for omni-channel consumption and manage the lifecycle of those APIs.
application-logs           lite                                            Create, store, access, and analyze application logs.
auditlog-management        default                                         Retrieve logs and change retention
business-rules             lite                                            Enrich cloud offerings with decision modelling and business rule management service
connectivity               lite                                            Establishes a secure and reliable connectivity between cloud applications and on-premise systems.
content-assembly-service   standard                                        This service packages a content into MTAR and exporting it to the corresponding Transport Mechanisms (CTS+/TMS)

**destination                lite, admin                                     Provides a secure and reliable access to destination and certificate configurations**

enterprise-messaging       dev                                             Connect applications, services and systems across different landscapes.
hanatrial                  hdi-shared, schema, securestore                 Manage Schemas and HDI Containers on a shared SAP HANA database
html5-apps-repo            app-host*, app-runtime                          Enables storage of HTML5 applications and provides runtime environment for HTML5 applications.
it-rt                      integration-flow                                Provides access to Process Integration runtime
malware-scanner            external                                        Scan single files for threats, via HTTP
mobile-services            lite                                            Build and run mobile apps.
saas-registry              application                                     Service for application providers to register multitenant applications and services
service-manager            subaccount-admin, subaccount-audit, container   Gives access to Service Manager APIs.
workflow                   lite                                            Automate business processes using workflow technology.
xsuaa                      space, application, broker, apiaccess           Manage application authorizations and trust to identity providers.

* These service plans have an associated cost. Creating a service instance will incur this cost.

TIP:  Use 'cf marketplace -s SERVICE' to view descriptions of individual plans of a given service.

I also performed this command -> cf create-service destination lite myDest

and it worked. I got an OK back. 

Does that mean I can continue on now? 

Thanks
Phil

**Comment by pjcools** [comment] 2020-04-18 04:57
I increased the quota by 1 for the destination service and still not working. 

Creating service "dest_tutorial" from MTA resource "dest_tutorial"...Service operation failed: Controller operation failed: 404 Updating service "dest_tutorial" failed: Not Found: Error creating service "dest_tutorial" from offering "destination" and plan "lite": Service plan lite not found. To download the process logs, use the "cf dmol -i 9214bcc4-812f-11ea-892b-eeee0a9b04de" command in the Cloud Foundry CLI directly in your Cloud Foundry space.See https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e93b231895b64cbc9221a62953563a6f.html.Job failed.
2:46:46 PM (DeploymentToCF) Deployment of the "tutorial" project failed.(Response state is FAILED)

There is something seriously wrong with this. 

thanks
Phil

**Comment by IObert** [comment] 2020-04-20 08:07
Ok, so the provisioning seems to work when you create the service manually. 
Can you try to remove the service you just created:
`cf delete-service -f myDest`
and create a new one with the name of the tutorial:
`cf create-service destination lite dest_tutorial`
Then you should be able to deploy the app but this is just a workaround.
This is a really strange situation. Is it possible that your Web IDE points to an old, invalid CF target or space?

**Comment by RedR4bb1t** [comment] 2020-04-20 15:03
I have the same problem

**Comment by federicof-protech** [comment] 2020-04-20 17:02
Hi, we have the same problem. 
We are using cf plugin from cmd to deploy and destination seems to disappear from marketplace offering in cloud foundry. It's happening for a week now, there are certain times when the service appears by itself.
![image](https://user-images.githubusercontent.com/53906398/79778442-1cd9b800-830f-11ea-955c-246270254da2.png)
Same if we try too look for it in cmd.
![image](https://user-images.githubusercontent.com/53906398/79778679-8659c680-830f-11ea-932e-dd6a61bc9cd1.png)
![image](https://user-images.githubusercontent.com/53906398/79778710-91145b80-830f-11ea-89a9-a9aff678120e.png)
We have already checked the entitlements, they are ok.
Our CF Region is eu10 Frankfurt provided by AWS.

Regards.

**Comment by IObert** [comment] 2020-04-21 10:28
Thanks for providing the detailed info. I'll try to reach out internally to get the problem fixed

**Comment by MichaelCzcz** [comment] 2020-04-24 12:53
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by pjcools** [comment] 2020-04-26 09:33
I followed the steps @IObert but still the same issue. I cannot seem to get past this! 

Creating service "dest_tutorial" from MTA resource "dest_tutorial"...Service operation failed: Controller operation failed: 404 Updating service "dest_tutorial" failed: Not Found: Error creating service "dest_tutorial" from offering "destination" and plan "lite": Service plan lite not found. Processing service "uaa_tutorial"...To download the process logs, use the "cf dmol -i 496eda27-87a0-11ea-9b4f-eeee0a81da5b" command in the Cloud Foundry CLI directly in your Cloud Foundry space.See https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e93b231895b64cbc9221a62953563a6f.html.Job failed.
7:28:45 PM (DeploymentToCF) Deployment of the "tutorial" project failed.(Response state is FAILED)

Anything else I can do??

**Comment by IObert** [comment] 2020-04-27 08:29
I'm sorry you're still facing this issue. It seems that there are multiple people encountering the same issue. However, it works on my landscapes.

As I said, I tried to find the root cause of this internally but it is quite hard if I cannot reproduce the problem at all. I'd like to ask you (@pjcools  @federicof-protech @RedR4bb1t ) to open tickets for this issue if you see it in production/paid landscapes. This might be the fastest way to get support.

**Comment by enchobelezirev** [comment] 2020-04-28 07:10
Hello colleagues,

I am from the CF deploy-service team responsible for the development of the cf deploy cli commands.
On which landscape you are trying to deploy? Could you give me the API ?
Something more, could you give me access in one of those spaces where the commands `cf martketplace` and `cf create-service ...` are working but the deployment is not working?

Thanks,
Encho

**Comment by IObert** [comment] 2020-04-28 09:26
I see, yes this is a problem. 
For now, I'd recommend removing the `ui5-middleware-cfdestination` middleware from the `ui5.yaml`. I'll work on a fix for the middleware.

**Comment by jonkerpeter** [comment] 2020-04-30 11:18
Hello colleagues,
I seem to have the same problem when deploying BPMServicesFLP_0.0.1.mtar in the tutorial Set Up Business Process Management Services in Cloud Cockpit.
Error message:
Error creating service "workflow" from offering "workflow" and plan "lite": Service plan lite not found. 
I have manually created the service instance workflow in the hope this would work, but manually creating the service instance did not solve this. workflow/lite is available with cf marketplace.
The first error message I received (before manually creating service instance workflow) was:
Could not bind application "BPMServicesFLP_appRouter" to service "workflow": 409 Conflict: CF-AsyncServiceInstanceOperationInProgress(60016): An operation for service instance workflow is in progress. Although this was the first time that I used the service workflow, so it could not be in use already as the error stated.
Any clues what to do ?

**Comment by federicof-protech** [comment] 2020-04-30 11:37
Update: On Tuesday 22/04 service with our cf environment (Frankfurt AWS) was unstable (services disappearing randomly, most related with html-repo-host) but the problem with the offering on destination was solved.
At the moment we aren't facing any trouble with services offering.

What we did when the service couldn't be created on deploy was defining it as a org.cloudfoundry.existing-service and link it to the existing service, but please take on consideration that It only works if you have already created the service before deploying.

Regards.

**Comment by samantak123** [comment] 2020-05-25 05:48
Hi Marius,

I am facing a somewhat similar kind of problem while deploying the UI5 Application to CF. Please find the screen shot of the detail below.

3:39:38 PM (DeployService) Target: https://deploy-service.cfapps.eu10.hana.ondemand.com/slprot/P199106trial_trial/dev/slpPreparing to deploy /tutorial/mta_archives/tutorial_0.0.1.mtarPrepare deployment filesChecking if there are conflicting processesFound 2 conflicting processesAborting process 1e80cc9c-9e49-11ea-ad41-eeee0a885b7cAborting process 240ae8cd-9e48-11ea-b183-eeee0a9da8b4Uploading mtar archiveStarting deploymentDeploying in org "P199106trial_trial" and space "dev"Detected MTA schema version: "3"No deployed MTA detected - this is initial deploymentDetected new MTA version: "0.0.1"Processing service "dest_tutorial"...Creating service "dest_tutorial" from MTA resource "dest_tutorial"...Processing service "uaa_tutorial"...Service operation failed: Controller operation failed: 403 Updating service "dest_tutorial" failed: Forbidden: Error creating service "dest_tutorial" from offering "destination" and plan "lite": CF-NotAuthorized(10003): You are not authorized to perform the requested action Setting service "uaa_tutorial" parameters from "xs-security.json"To download the process logs, use the "cf dmol -i 1a450264-9e4a-11ea-ad41-eeee0a885b7c" command in the Cloud Foundry CLI directly in your Cloud Foundry space.See https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e93b231895b64cbc9221a62953563a6f.html.Job failed.
3:39:38 PM (DeploymentToCF) Deployment of the "tutorial" project failed.(Response state is FAILED)

Any pointer will be very helpful. 

Thanks,
Sam.

**Comment by boyan-velinov** [comment] 2020-05-27 11:54
Hello,

I am afraid that several problems are described in the current github issue. Most of them are related to creation of service instance but they have very different root causes. I will try to summarise different problems and provide the right direction for each of them.

1. `Could not create service instance "dest_tutorial". Service plan "lite" from service offering "destination" was not found.` -> problem with quota assignment for destinations service. normally it should be configured within Cockpit

2. `Could not bind application "BPMServicesFLP_appRouter" to service "workflow": 409 Conflict: CF-AsyncServiceInstanceOperationInProgress(60016): An operation for service instance workflow is in progress` -> this was a regression in MTA Deployment side where creation of async services were not handled properly and deployment continue without waiting them to finish. As a result you could experience similar error on different steps during deployment. Note that this is fixed already and must not appear anymore.

3. Error creating service "dest_tutorial" from offering "destination" and plan "lite": CF-NotAuthorized(10003): You are not authorized to perform the requested action -> seems as you don't have the right permissions. Make sure you have `SpaceDeveloper` role in the space where you perform the deployment.

One suggestion from my side - if creation of service fails during MTA deployment, you can perform initial troubleshooting to understand if the problem is quota assignment, service broker or MTA deployment. To accomplish that, just try to create the service with the same parameters. You can do it in Cockpit or with `cf create-service `

In my understandings, the initial issue with quota assignment is resolved, so let's close this issue and if you have different questions, open a new issue for each of them.


Best Regards,
Boyan

**Closed** 2020-05-27 12:44 UTC

**Comment by Jr-zero** [comment] 2021-04-29 05:59
Could not create service instance "dest_tutorial". Service plan "lite" from service offering "destination" was not found. 
In the command: `cf html5-list -di sap-btp-sapui5-dest-srv -u --runtime launchpad` just enter the name of your service instance.
Example: Service Instance: sap-btp-sapui5-dest-srv
Command: `cf html5-list -di sap-btp-sapui5-dest-srv -u --runtime launchpad`

![image](https://user-images.githubusercontent.com/4356842/116507921-a020d880-a896-11eb-8901-cdfd428d5350.png)

![image](https://user-images.githubusercontent.com/4356842/116508072-ee35dc00-a896-11eb-9d83-798e3ce8123f.png)

**Comment by MiqueiasMaia** [comment] 2021-11-23 18:06
Anybody solved it?

**Comment by 0anton** [comment] 2022-12-08 08:49
I'm facing the same issue. Looks like something is going wrong with the destination creation.
Does anybody knows how to fix it?
I've created an issue to the same: https://github.com/SAP-samples/multi-cloud-html5-apps-samples/issues/50
