### ISSUE TITLE
Build Luigi App with React

### ISSUE THREAD

**Issue by charles0488** [SAPDocuments/Tutorials#6317] opened 2020-12-09 22:35 UTC
Tutorial URL: https://developers.sap.com/tutorials/luigi-app-react.html

Please specify the step you are referring to
npm run eject

> react-core-mf@0.1.0 eject
> react-scripts eject

NOTE: Create React App 2+ supports TypeScript, Sass, CSS Modules and more without ejecting: https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

✔ Are you sure you want to eject? This action is permanent. … yes
This git repository has untracked files or uncommitted changes:

package-lock.json
M package.json
ui5-mf/

Remove untracked files, stash or commit any changes, and try again.
npm ERR! code 1
npm ERR! path /Users/i833567/luigi/luigi-react-ui5/react-core-mf
npm ERR! command failed
npm ERR! command sh -c react-scripts eject

npm ERR! A complete log of this run can be found in:

**Comment by thecodester** [comment] 2020-12-20 09:16
@alexandra-simeonova  Can you respond?

**Comment by alexandra-simeonova** [comment] 2020-12-21 07:24
Hi,
it seems like this error might be caused by not commit changes first before running the command. https://stackoverflow.com/questions/45671057/how-to-run-eject-in-my-react-app
Please try again after committing, thank you.

**Comment by MichaelCzcz** [comment] 2021-01-05 10:36
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2021-01-05 10:36 UTC
