### ISSUE TITLE
Create a Theme for Your Portal Freestyle Site

### ISSUE THREAD

**Issue by RubenRollano** [SAPDocuments/Tutorials#3524] opened 2019-05-21 06:40 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-freestyle-site-brand-site.html

In the step 6, the Theme Manager dosen't load properly.

https://flpportal-p1940438444trial.dispatcher.hanatrial.ondemand.com/sites/designer?siteId=2f477852-441e-4a68-bf2b-99e28410e77b#ThemeManager-Manage

![image](https://user-images.githubusercontent.com/25760588/58073850-04fc3000-7ba4-11e9-827e-2dae8454f212.png)

**Comment by LindsayBert** [comment] 2019-06-19 13:03
Hi

Please open a ticket for the development team using this component: EP-CPP-NEO-FCC.
Write in the description that the issue is with the Theme Manager.

With thanks
Lindsay Bert

**Comment by thecodester** [comment] 2019-06-24 04:35
Thanks for the feedback. I am closing the issue since for now there is nothing else to do with the tutorial.

**Closed by thecodester** 2019-06-24 04:35 UTC
