### ISSUE TITLE
Installing SAP HANA, express edition with Docker - ERROR: Insufficient permissions on /hana/mounts. Required permissions: rwx

### ISSUE THREAD

**Issue by the1bit** [SAPDocuments/Tutorials#3065] opened 2019-02-11 12:21 UTC
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html

I have an issue at Step 8: Start SAP HANA, express edition Container, when I execute the command:

```
docker run -p 39013:39013 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v /data/saphana:/hana/mounts \
--ulimit nofile=1048576:1048576 \
--sysctl kernel.shmmax=1073741824 \
--sysctl net.ipv4.ip_local_port_range='40000 60999' \
--sysctl kernel.shmmni=524288 \
--sysctl kernel.shmall=8388608 \
--name saphanaexpress01 \
store/saplabs/hanaexpress:2.00.033.00.20180925.2 \
--passwords-url file://data/masterpwd.json \
--agree-to-sap-license
```
Error message: **ERROR: Insufficient permissions on /hana/mounts. Required permissions: rwx**
```
======== Starting HANA container run script ========
Started at: Mon Feb 11 12:09:24 UTC 2019
Script parameters: --passwords-url file://data/masterpwd.json --agree-to-sap-license
HANA version: 2.00.033.00.1535711040
Linux kernel version: 4.9
New host: '19eddacfba7f'
Setting HANAs host name to '19eddacfba7f' ...
Checking allowed mountpoints ...
ERROR: Insufficient permissions on /hana/mounts. Required permissions: rwx
```

Tryings, which don'4 work:

- I tried execute command in name of root
- I tried execute command in name of non-root user
- I modified the permission of **/data/saphana** to 777
- I modified the permission of **masterpwd.jso**n to 777

Please help me to solve this issue.

Other information:
- Base OS: Ubuntu 18.04 LTE (WSL on W10)
- Docker version: 18.09.1, build 4c52b90

Feel free to get in touch with any questions.

Thank you for your help in this matter.

**Comment by TerryNing** [comment] 2019-02-12 14:53
Try to change:

-v /data/saphana:/hana/mounts --passwords-url file://data/masterpwd.json
==>
-v /data/saphana:/hana/mounts --passwords-url file:///hana/mounts/masterpwd.json

**Comment by the1bit** [comment] 2019-02-13 08:19
Hi,

Thank you for your response.
I made the changes but the result is same:
```
======== Starting HANA container run script ========
Started at: Wed Feb 13 08:14:17 UTC 2019
Script parameters: --passwords-url file://hana/mounts/masterpwd.json --agree-to-sap-license
HANA version: 2.00.033.00.1535711040
Linux kernel version: 4.9
New host: 'b0efcf7ab7da'
Setting HANAs host name to 'b0efcf7ab7da' ...
Checking allowed mountpoints ...
ERROR: Insufficient permissions on /hana/mounts. Required permissions: rwx
```

Command:
```
docker run -p 39013:39013 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v /data/saphana:/hana/mounts \
--ulimit nofile=1048576:1048576 \
--sysctl kernel.shmmax=1073741824 \
--sysctl net.ipv4.ip_local_port_range='40000 60999' \
--sysctl kernel.shmmni=524288 \
--sysctl kernel.shmall=8388608 \
--name saphanaexpress01 \
store/saplabs/hanaexpress:2.00.033.00.20180925.2 \
--passwords-url file://hana/mounts/masterpwd.json \
--agree-to-sap-license
```

Do you have any other idea?

Thank again.

**Comment by TerryNing** [comment] 2019-02-13 08:44
@the1bit 

file://hana/mounts/masterpwd.json
==>
file:///hana/mounts/masterpwd.json

(file:///, 3 '/' , you could consider it as file:// + /hana/mounts/masterpwd.json )

**Comment by the1bit** [comment] 2019-02-13 09:55
Great. I executed the fixed script and the result is same:
```
======== Starting HANA container run script ========
Started at: Wed Feb 13 09:54:08 UTC 2019
Script parameters: --passwords-url file:///hana/mounts/masterpwd.json --agree-to-sap-license
HANA version: 2.00.033.00.1535711040
Linux kernel version: 4.9
New host: 'd57491bc0345'
Setting HANAs host name to 'd57491bc0345' ...
Checking allowed mountpoints ...
ERROR: Insufficient permissions on /hana/mounts. Required permissions: rwx
```

**Comment by TerryNing** [comment] 2019-02-13 12:47
maybe redundant check, could you execute
    ls -l  /data
    ls -l  /data/saphana

Also the tutorial link mentioned two related operations, I assume you also tried before trying 777
    sudo chmod 600 /data/<directory_name>/<file_name>.json
    sudo chown 12000:79 /data/<directory_name>/<file_name>.json

**Comment by the1bit** [comment] 2019-02-13 13:14
I executed these:
```
sudo chmod 600 /data/<directory_name>/<file_name>.json
sudo chown 12000:79 /data/<directory_name>/<file_name>.json
```
Results:
```
ls -l /data
total 0
-rwxrwxrwx 1 12000 79   49 Feb 11 13:08 masterpwd.json
drwxrwxrwx 1 12000 79 4096 Feb 11 13:09 saphana
```
```
ls -l /data/saphana
total 0
-rw------- 1 12000 79 49 Feb 11 13:09 masterpwd.json
```

Nevertheless the docker result is same:
```
======== Starting HANA container run script ========
Started at: Wed Feb 13 13:13:31 UTC 2019
Script parameters: --passwords-url file:///hana/mounts/masterpwd.json --agree-to-sap-license
HANA version: 2.00.033.00.1535711040
Linux kernel version: 4.9
New host: '554cff20c68e'
Setting HANAs host name to '554cff20c68e' ...
Checking allowed mountpoints ...
ERROR: Insufficient permissions on /hana/mounts. Required permissions: rwx
```

**Comment by rericsson** [comment] 2019-02-21 11:21
I was able to use the URL option to get the install to work. I used http://myjson.com to store the snippet of JSON containing the password and then used the following:

docker run -p 39013:39013 -p 39015:39015 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014  -p 39030-39033:39030-39033 -p 51000-51060:51000-51060  -p 53075:53075  \
-h hxehost \
--ulimit nofile=1048576:1048576 \
--sysctl kernel.shmmax=1073741824 \
--sysctl net.ipv4.ip_local_port_range='60000 65535' \
--sysctl kernel.shmmni=524288 \
--sysctl kernel.shmall=8388608 \
--name express_edition \
store/saplabs/hanaexpressxsa:2.00.035.00.20190115.1 \
--agree-to-sap-license \
--passwords-url https://api.myjson.com/bins/1844hs/

It takes quite a while (~30 minutes) but succeeded eventually.

**Comment by the1bit** [comment] 2019-02-25 15:23
Hi @rericsson,

I tried your solution and it seems work. :-)

Nevertheless the official documentation is different and this is my biggest pain point. So thank you so much for your help. I am waiting for a working documentation. ;-) I am sure @TerryNing will be able to support me and the community.

Thank you for all of your help.

**Comment by the1bit** [comment] 2019-02-25 22:00
Hi All,

Finally I stepped back to the original command (of course I used @rericsson's example) and I got rid of "-v" part of script.

So I executed this:

```
docker run -p 39013:39013 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 \
--ulimit nofile=1048576:1048576 \
--sysctl kernel.shmmax=1073741824 \
--sysctl net.ipv4.ip_local_port_range='40000 60999' \
--sysctl kernel.shmmni=524288 \
--sysctl kernel.shmall=8388608 \
--name saphanaexpress01 \
store/saplabs/hanaexpress:2.00.033.00.20180925.2 \
--passwords-url https://the1bithusadev.blob.core.windows.net/saphana/masterpwd.json \
--agree-to-sap-license
``` 

Surprisingly it works. :-)

@TerryNing: Colud you please help me to understand why it goes to fail the command when we use "-v /data/saphana:/hana/mounts"?

Thanks in advance.

**Comment by rericsson** [comment] 2019-02-26 13:32
The -v option is for bind mounting to a folder on the host.  I'm not sure why it would fail but I always got a permissions problem on the password JSON file. I suppose it has something to do with the user accessing the file, but I could never get it to work even after opening the file to world+dog, so I tried the http option and that worked so I didn't pursue it. Maybe someone more steeped in the ways of docker bind mounting would know offhand. 

Rob

**Comment by thecodester** [comment] 2019-04-22 12:43
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

Feel free to continue the discussion in the SAP Community or in the SAP Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html

**Closed by thecodester** 2019-04-22 12:43 UTC

**Comment by the1bit** [comment] 2019-04-23 07:05
Hi,

The installation does not work according to documentations.  From that point of view the issue is not solved.

I would like to ask you to update the documentation.

Thank you for your help.

BR,
TB

**Comment by thecodester** [comment] 2019-04-23 09:06
@JCurrie27 @TerryNing Can you address?

@the1bit When you say the documentation needs fixing, which documentation? Link?

**Comment by JCurrie27** [comment] 2019-04-23 12:34
@thecodester: The documentation in question is cited earlier in this thread. The bind mounting command 
... -v /data/saphana:/hana/mounts ...
works for some users and fails for others -- this requires further investigation by @TerryNing's team before the tutorial [https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html](https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html) can be updated with either an updated command, or a workaround for users with a particular environment.

**Comment by atif92** [comment] 2019-06-19 12:00
I am having the same issue with using -v , even though my json is remotely located. If this continues how can we actually mount the data to SAPHANA DB? how would we be able have permanent data?

**Comment by smartexpert** [comment] 2019-11-26 21:37
Confirm that the string with mount is an absolute path. I resolved my issue by putting the right path after -v e.g. this how that line looks like in my setup"
` -v /drive/docker/volumes/HXE_DOCKER1:/hana/mounts`

**Comment by emredmrl** [comment] 2020-01-25 15:17
The issue is still happening. We cannot consider it closed. You have to remove -v option (which means you have to give up host stored data folder)  and also do   @rericsson  suggested. 
This means documentation is wrong and results in a very time consuming set of garbage activities. 
Thanks everybody in this post. You helped me get the things done at least.

**Comment by thecodester** [comment] 2020-01-26 06:01
@JCurrie27 @emredmrl "Documentation" is mentioned several time, but there is no link to this documentation. Do you mean the text of the tutorial, or do you mean information at https://help.sap.com (which is the official documentation)?

**Comment by emredmrl** [comment] 2020-01-26 08:37
Yes, you are right. I meant docker setup instructions.

https://hub.docker.com/_/sap-hana-express-edition/plans/f2dc436a-d851-4c22-a2ba-9de07db7a9ac?tab=instructions

**Comment by thecodester** [comment] 2020-01-26 08:41
OK, I understand now. @JCurrie27 Any update on this?

**Comment by JCurrie27** [comment] 2020-01-27 15:27
This thread is discussing two separate documents:

- The developer tutorial on the SAP site: [https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html](https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html)
- The installation instructions on Docker Hub: [https://hub.docker.com/_/sap-hana-express-edition/plans/f2dc436a-d851-4c22-a2ba-9de07db7a9ac?tab=instructions](https://hub.docker.com/_/sap-hana-express-edition/plans/f2dc436a-d851-4c22-a2ba-9de07db7a9ac?tab=instructions)
These two documents have drifted out of alignment over time. The former is more up-to-date.

1. I'm aligning the Docker Hub instructions with the developer tutorial
2. I'm taking these -v command issues above to the Shanghai team to investigate and run tests. I'll update both documents depending on the testing outcome. Chinese New Year will delay us here somewhat.

**Comment by jyothiradityak** [comment] 2020-03-07 16:21
hi experts,

Even i am trying as per tutorial and getting same error. 

sudo docker run -p 39013:39013 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v /data/dockersapexpr:/hana/mounts \
--ulimit nofile=1048576:1048576 \
--sysctl kernel.shmmax=1073741824 \
--sysctl net.ipv4.ip_local_port_range='40000 60999' \
--sysctl kernel.shmmni=524288 \
--sysctl kernel.shmall=8388608 \
--name express_Edition3 \
store/saplabs/hanaexpress:2.00.045.00.20200121.1 \
--passwords-url https://api.myjson.com/bins/xxxx \
--agree-to-sap-license

And still  getting same error. can you please guide how to fix it ?

regards,
aditya

**Comment by JCurrie27** [comment] 2020-03-08 18:17
Hi aditya: Could you please post this error scenario on the HANA Express Q&A page? That page is actively monitored by experts, and by the user community:

- Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
- Add a title. Add the details cited above
- In the **Select a Primary Tag** field, search for "express" and select "SAP HANA, express edition"

Many thanks.

**Comment by sstadelman** [comment] 2020-09-15 22:18
I encountered the same, any update?

**Comment by jorgt** [comment] 2020-12-23 03:19
Still happening here, too.

**Comment by jrodriguez-rc** [comment] 2020-12-30 14:26
I had the problem, fixing it setting chmod -R 777 /data/hana

It seems that all the content in the folder needs to be rwx

**Comment by shashankraj1987** [comment] 2021-09-25 17:36
> Still happening here, too.
> 
> In my case, a SELinux issue:
> 
> rule `chcon -Rt svirt_sandbox_file_t /data` got it working.

This saved me. Got me working on Fedora 34. Thanks.

**Comment by Rufin20** [comment] 2023-04-05 14:47
To fix this issue, just change the owner of /data/hana to the id of user used inside the container:

`sudo chown 12000:79 /data/hana`
