### ISSUE TITLE
Build Skeleton React and UI5 Projects

### ISSUE THREAD

**Issue by charles0488** [SAPDocuments/Tutorials#6316] opened 2020-12-09 22:34 UTC
Tutorial URL: https://developers.sap.com/tutorials/luigi-app-basic-setup.html

Please specify the step you are referring to
npm i -P @luigi-project/core @luigi-project/client fundamental-styles fundamental-react @sap-theming/theming-base-content react-router-dom
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-core-mf@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from fundamental-react@0.13.1
npm ERR! node_modules/fundamental-react
npm ERR!   fundamental-react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/i833567/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

**Comment by thecodester** [comment] 2020-12-20 09:16
@alexandra-simeonova  Can you respond?

**Comment by alexandra-simeonova** [comment] 2020-12-22 10:25
Hello,

This issue is caused by not having the latest npm version installed. (https://www.gitmemory.com/issue/npm/cli/2119/721608949)
Please run `npm install npm@latest -g` first and try again. 
Thank you for checking out the tutorial.

**Comment by MichaelCzcz** [comment] 2021-01-05 10:36
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2021-01-05 10:36 UTC
