### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#6152] opened 2020-11-12 06:41 UTC
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Step 9 - Sub step 5. 

The page is not getting loaded, a blank screen is appearing on both the EU and US landscapes. Please check the below snapshot  of console error.

![image](https://user-images.githubusercontent.com/65213299/98904488-b94bed80-24df-11eb-8faf-c44f3970aefc.png)

Labels :
Landscape Labels: trail1, trail2
SCPTest-eboard: Develop a Fiori App Using ABAP
Priority label :‘High-prio’

Best Regards,
Shivakumar P

**Comment by mervey45** [comment] 2020-11-13 13:34
Hi @shivakumar-p-sap ,

did you create this scenario from scretch? Or did you tried to load the page again?

Best regards, 
Merve

**Comment by shivakumar-p-sap** [comment] 2020-11-13 15:58
Hi Merve Temel,

I created the scenario from scratch only. It was showing blank. After sometime when page was not getting loaded then only i tried to reload the page.

Thanks and Regards
Shivakumar P

**Comment by mervey45** [comment] 2020-11-19 15:53
Hi @shivakumar-p-sap ,

do you also run your console application? You need to do: https://developers.sap.com/tutorials/abap-environment-persistence.html  Step 3.4.
If you don't run your ABAP class, your tables won't be filled and you don't see anything. 

Best regards, 
Merve

**Comment by shivakumar-p-sap** [comment] 2020-11-20 04:31
Hi Merve Temel,

Yes. I run the console application and i could also able to see the table contents after that only i continued with further tutorials.

Thanks and Regards
Shivakumar P

**Comment by mervey45** [comment] 2020-11-27 15:02
Hi @shivakumar-p-sap ,

here seems to be some issues with the deployment. We are trying to fix it. I will update this tutorial, as soon as the issue is solved.

Thank you for your understanding.

Best regards, 
Merve

**Comment by mervey45** [comment] 2020-12-10 08:03
Hi @shivakumar-p-sap ,

we have following ticket regrading this issue opened: https://github.wdf.sap.corp/ux-engineering/tools-suite/issues/10358.
@MichaelCzcz we can close this issue.

Thank you for your understanding.

Best regards, 
Merve

**Closed** 2020-12-20 08:32 UTC
Labels: High-Prio, SCPTest-2010A, SCPTest-fabap, SCPTest-trial1, SCPTest-trial2

**Comment by i353590** [comment] 2020-12-22 08:59
Hello @mervey45, 

The ticket that you mentioned was closed around 20 days back saying the issue is resolved, and I have retested the scenario on 10th December, till then the issue was still there.

Could you please check once again?

thanks,
Shubham
