### ISSUE TITLE
Integrate an SAP Fiori App into Your Portal Site (Cloud Foundry)

### ISSUE THREAD

**Issue by stesap** [SAPDocuments/Tutorials#4162] opened 2019-11-06 11:37 UTC
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-sapui5-app.html

Hi all,

after I went through the whole mission twice, I still get a none verbose error message after I click on the tile which is linked in the Portal (tenant):

<img width="749" alt="Screenshot 2019-11-06 at 11 02 25" src="https://user-images.githubusercontent.com/57390068/68288757-49618680-0085-11ea-927d-6fa6dc1e7423.png">

BTW it is not the Trial account. It's intended to be deployed as a real app.
When I use the link from this [cp-cf-fioriapps-create](https://developers.sap.com/tutorials/cp-cf-fioriapps-create.html) tutorial, the app is accessible.

When I edit the tile in the Portal from `In place` to `In a new tab`, the app is opened successfully in a new tab. Though, we want to open all apps within the launchpad.

I saw in developer console of Chrome, the following error:
> Refused to display 'https://tenant-dev-mta-webui5app-approuter.cfapps.eu10.hana.ondemand.com/cp.portal/ui5appruntime.html?sap-ui-app-id=com.secret.industries..webUi5App&sap-startup-params=&sap-language=en&sap-shell=FLP&sap-theme=sap_fiori_3#object1-action1?sap-ui-app-id-hint=00001111' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

My understanding is that the usage of the **destination** for the app (which is deployed in a specific space), the app always runs within the same origin. No matter which endpoint the destination targets.

I tried to set the tile configuration for the app as direct URL (full path with `<prefix>/index.html` at the end. It doesn't work, I think because of the origin issue, which is fine in this case.

Thanks
Steffen

**Comment by IObert** [comment] 2020-01-08 10:46
Hi Steffen,


This error is intended and not a bug. Destinations in the destination service are, technically speaking, just strings that are stored. The "hiding" behind the same origin is a feature of the approuter that is a consumer of the destination service.

If you want to display your own web apps as URL apps, they need to allow being displayed in an iframe with the `X-Frame-Options` header. This header has to have a value similar to this one: `ALLOW-FROM http://localhost`.

If you are using the approuter to serve your web app, you can set an environment variable to: `SEND_XFRAMEOPTIONS=false`
or
`httpHeaders=[{"X-Frame-Options": "ALLOW-FROM https://launchpadURL.com"}]`

**Comment by MichaelCzcz** [comment] 2020-01-16 08:52
@stesap Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-01-16 08:52 UTC

**Comment by vbalko** [comment] 2020-09-02 19:09
That solution with ALLOW-FROM http://localhost is not plausible anymore. Option ALLOW-FROM is deprecated. Is there other solution?

**Comment by henningrettenmaier** [comment] 2021-02-17 14:38
Hi all, I'm doing an integration to SAP WorkZone which is technically the same and I receive a 403 error. Do I need to set some permissions ?
