### ISSUE TITLE
Image Classification ML service with SAPUI5

### ISSUE THREAD

**Issue by swapnilspande** [SAPDocuments/Tutorials#2029] opened 2017-11-15 14:00 UTC
Hi Abdel,

Thanks for providing a step-by-step guide, it really helped understand each step.

I followed each step, however, when I run the SAPUI5 application, it gives 400(Bad Request) error.

Below is the error the service returns.
"error_description": "This service requires at least 1 file. Please put your file(s) into the `files` field of the POST request", 
 
It would be really helpful, if you can provide some pointers on this.

Thanks,
Swapnil.

**Comment by swapnilspande** [comment] 2017-11-16 16:40
I just found out that the error that I am getting is similar to the one mentioned in issue no. 1864, which is also open.
**Image Classification ML service with SAPUI5 #1864**

**Comment by adadouche** [comment] 2017-12-07 09:55
Duplicate of Image Classification ML service with SAPUI5 #1864

**Closed by adadouche** 2017-12-07 09:55 UTC
