### ISSUE TITLE
Build OData Queries with the SAP Cloud SDK's Virtual Data Model

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4611] opened 2020-02-10 15:56 UTC
Tutorial URL: https://developers.sap.com/tutorials/cloudsdk-js-vdm-getall.html

Step 11: Test yourself

I've just went through this tutorial and answered the first question of the Self Test. By submitting the correct answer the two other questions where also marked as "Your answer is correct":

![Screenshot 2020-02-10 at 16 53 14](https://user-images.githubusercontent.com/2639535/74165987-2e735500-4c26-11ea-9dbe-0ad2c8b8aab5.png)

**Comment by sacnl** [comment] 2020-02-12 07:41
@thecodester can you comment if that is expected behavior when grouping several questions into one step? Should we rather split those into separate steps?

FYI @FrankEssenberger

**Comment by FrankEssenberger** [comment] 2020-02-12 07:59
I already received feedback before @thecodester , that only one validate per step should be use. I changed it to `Test yourself I`, `Test yourself II` and `Test yourself III`. Not very nice, but what I got in the discussion there is no sub-step which can be used to seperate the validate parts.

**Comment by thecodester** [comment] 2020-02-12 08:10
Only one validation question is allowed per step -- I had a discussion with Frank a few days ago. If you want multiple questions, either put them in previous steps, or add a step for each one. Though having them in one step would be more elegant, multiple steps is not terrible. I have added this feature to our backlog.

I believe Frank has already started to modify this tutorial in QA.

@mr-flannery

**Comment by thecodester** [comment] 2020-02-12 08:17
Also, please test your tutorial, including the validation, before pushing to production. I always suggest the author test, as well as one or more additional people.

If you want to test the validation repeatedly, you can clear your progress in the QA Developers Center home page. Once you complete a step, it will always be completed unless you clear your progress. DON'T DO THIS IN PRODUCTION.

**Comment by MichaelCzcz** [comment] 2020-03-06 10:01
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2020-03-06 10:01 UTC
