### ISSUE TITLE
Grunt Build in SAP Web IDE

### ISSUE THREAD

**Issue by hschaefer123** [SAPDocuments/Tutorials#2312] opened 2018-04-17 09:22 UTC
Hi,
thanks for making CachebusterInfo.json available in @sap/grunt-sapui5-bestpractice-build": "1.3.50.

Building outside WebIDE there is currently an issue inside task **devx-updateNeoApp**!

The path is only correctly resolved on windows and not on Linux!

On windows my neo-app.json
"welcomeFile": "/webapp/index.html",
will be correctly changed to 
"welcomeFile": "/index.html",

but this does not work for our CI/DI on Linux!

Maybe inside 
var sSourceFolderRelativePath = "/" + grunt.config.data.dir.appFolder;
the appFolder is not relative on Linux and therefore this does not work.

It would be great to get that fixed, because we are developing locally and building/deploying it to MTA using git pipeline.

BTW: Do you have any info how to use the new feature
>task for building an HTML5 module inside full-stack projects. The build results are stored as part of the .mtar file.

Please let me know the fixed version number.

Thanks 
Holger

**Comment by themasch** [comment] 2018-04-17 12:09
I guess this problem resides in getComponentParent / getRootDir / isComponentInCurrentFolder. 

`getComponentParent` already has some special support for absolute paths but does this only for very special cases (webide?). 
Whap happens is, that `appFolder` (which is set to `componentParentDir`) happes to be something like this on linux: `/home/user/code/customer/project/webapp/`. 
`devx-updateNeoApp` tries to replace that whole thing in `oNeoAppJsonContent.welcomeFile`, which does not work since welcomeFile is something like `/webapp/index.html`. 

In previous versions appFolder (was then called webapp) was fixed to `/webapp` which is why it worked in this case. 

I have not found the exact point where the path resolution failes but getComponentParent is where I would start tracing the issue.

**Comment by avizov** [comment] 2018-04-18 06:41
Hi Holger,

This is a good point. I have observed more places in the grunt best practices that don't treat correctly the path resolution. We need to use Path.join() instead concatenation. I will open an internal ticket for that and let you know as soon as we release a fixed version. 

Thanks,
Alex

**Comment by gaiawork** [comment] 2018-05-06 10:32
Hi Holger,

A fix is available with @sap/grunt-sapui5-bestpractice-build version 1.3.55

Regards,
Gaia

**Comment by hschaefer123** [comment] 2018-05-07 07:38
Hi Gaia,
it is working as expected!

Thank you.

Currently the sap-ui-cachebuster-info.js is not generated if i deploy using SAP Web IDE Full-Stack.
Is SAP aware of this bug?

Regards Holger

**Comment by avizov** [comment] 2018-05-07 08:04
Hi Holger,

What do you mean "deploy using SAP Web IDE Full-Stack"? Do you mean deploy multi-target project (mta) project?

Thanks,
Alex

**Comment by hschaefer123** [comment] 2018-05-07 09:42
Hi Alex,
if i am building locally, it works for me.

Trying to deploying using the SAP Web IDE Full-Stack means i am using the new SAP Web IDE Full-Stack app inside SAP Cloud Plattform that uses build from grunt.loadNpmTasks("@sap/grunt-sapui5-bestpractice-build");

Since i am using the IDE integrated build process, i know that there is a special switch/case inside the grunt-sapui5-bestpractice-build. Doing it this way, there is no sap-ui-cachebuster-info.js  build/deployed to the corresponing html5 app. 

Inside the Web IDE Full Stack the formerly integrated build/deploy process have been removed/reworked by using more public node/grunt process (the same way i am using locally), but the generated/handled artifacts in the target html5 container differ from the one generated locally (in this case the missing sap-ui-cachebuster-info.js.

I hope, this is understandable.

Regards Holger

**Comment by avizov** [comment] 2018-05-07 13:57
Hi Holger,

I am not sure if I understood you right. But, I also success to build it locally and it worked for me (the cache buster file successfully created for me). If you do that from the Full Stack Web IDE (the build process) it also builds it correctly but you can't see the sap-ui-cachebuster-info.js file since this is very hidden file and therefore you can't see it in the file structure. The only way to see it is to export the project to your downloads and to open the archive file and then you will see it under the dist folder. 

Thanks,
Alex

**Comment by hschaefer123** [comment] 2018-05-07 15:54
Hi Alex,
first of all thanks for the hint, that even when selecting show hidden fields option in Web IDE, the cachebuster will not be shown (for whatever reason ;-)

If i export the project from web ide, i can see that ```/dist/sap-ui-cachebuster-info.js``` is part of the archieve,
but it seems to be missing in the scp deployed version.

An example for the issue is my current youtube control
https://github.com/hschaefer123/youtube

If i deploy this with Web IDE to SCP HTML5
https://youtube-p1940953245trial.dispatcher.hanatrial.ondemand.com/index.html

you will get an 404 eror on
https://youtube-p1940953245trial.dispatcher.hanatrial.ondemand.com/sap-ui-cachebuster-info.json?sap-ui-language=en

So i think, the Web IDE hide feature for special file extensions maybe hide/excludes this file also on deployment?!? ;-) From my point that can be the only reason for this, because build seems ok (even not seeable on IDE) but deployment of this file misses. 

Local deployment using 
```neo-java-web-sdk/tools/neo deploy-mta deploy-mta.properties```
is working as expected!

Can you confirm this, or did you get a Web IDE using CacheBuster on SCP running this way?

Regards Holger

**Comment by thecodester** [comment] 2018-06-27 09:16
@avizov Can you respond or close this issue? Thanks.

**Comment by avizov** [comment] 2018-06-27 09:52
Hi Holger,
I succeed to reproduce the issue the same as you described. Update you as soon as possible.
Thanks,
Alex

**Comment by thecodester** [comment] 2019-01-15 08:07
@avizov Was this resolved?

**Comment by thecodester** [comment] 2019-04-22 12:24
@jhornik Can you investigate this?

**Comment by jhornik** [comment] 2019-04-22 13:04
@thecodester Better if @avizov responds. He is probably on vacation until next week.

**Comment by hschaefer123** [comment] 2019-04-22 18:33
hi,
i can confirm that this has been fixed in the meantime.

Right now, i am using cachebuster feature in my deployed ui5 projects.
This was not recognized formerly because flp also has a custom cache feature.

Regards Holger

**Comment by avizov** [comment] 2019-04-23 05:22
Hi Holger,
So, can you close the ticket?
Thanks,
Alex

**Closed** 2019-04-23 07:16 UTC
